// US-S05-24: Generate compliance test suite from passport constraints

export interface TestGeneratorInput {
  readonly name: string;
  readonly permissions?: {
    readonly tools?: readonly string[];
    readonly denied?: readonly string[];
  };
  readonly constraints?: {
    readonly rate_limits?: readonly { action: string; limit: number; window: string }[];
    readonly prohibited_actions?: readonly string[];
    readonly escalation_rules?: readonly { condition: string; escalate_to: string }[];
    readonly budget?: { max_cost: number; currency: string };
  };
}

export interface GeneratedTestSuite {
  readonly filename: string;
  readonly content: string;
  readonly testCount: number;
}

export const generateComplianceTests = (input: TestGeneratorInput): GeneratedTestSuite => {
  const { name, permissions, constraints } = input;
  const lines: string[] = [];
  let testCount = 0;

  lines.push(`// Auto-generated compliance tests for agent: ${name}`);
  lines.push(`// Generated by Complior — DO NOT EDIT MANUALLY`);
  lines.push(`// Regenerate with: complior passport test-gen ${name}`);
  lines.push(`import { describe, it, expect } from 'vitest';`);
  lines.push('');
  lines.push(`describe('${name} compliance constraints', () => {`);

  // 1. Permission tests — allowed tools
  if (permissions?.tools?.length) {
    lines.push('');
    lines.push(`  describe('permissions.tools (allowed)', () => {`);
    for (const tool of permissions.tools) {
      lines.push(`    it('should allow tool: ${tool}', () => {`);
      lines.push(`      const allowed = ${JSON.stringify(permissions.tools)};`);
      lines.push(`      expect(allowed).toContain('${tool}');`);
      lines.push(`    });`);
      testCount++;
    }
    lines.push(`  });`);
  }

  // 2. Permission tests — denied tools
  if (permissions?.denied?.length) {
    lines.push('');
    lines.push(`  describe('permissions.denied (blocked)', () => {`);
    for (const tool of permissions.denied) {
      lines.push(`    it('should block tool: ${tool}', () => {`);
      lines.push(`      const denied = ${JSON.stringify(permissions.denied)};`);
      lines.push(`      expect(denied).toContain('${tool}');`);
      lines.push(`    });`);
      testCount++;
    }
    lines.push(`  });`);
  }

  // 3. Rate limit tests
  if (constraints?.rate_limits?.length) {
    lines.push('');
    lines.push(`  describe('rate limits', () => {`);
    for (const rl of constraints.rate_limits) {
      lines.push(`    it('should enforce rate limit: ${rl.action} <= ${rl.limit}/${rl.window}', () => {`);
      lines.push(`      const limit = ${rl.limit};`);
      lines.push(`      expect(limit).toBeGreaterThan(0);`);
      lines.push(`      expect(limit).toBeLessThanOrEqual(${rl.limit});`);
      lines.push(`    });`);
      testCount++;
    }
    lines.push(`  });`);
  }

  // 4. Prohibited action tests
  if (constraints?.prohibited_actions?.length) {
    lines.push('');
    lines.push(`  describe('prohibited actions', () => {`);
    for (const action of constraints.prohibited_actions) {
      lines.push(`    it('should prohibit: ${action}', () => {`);
      lines.push(`      const prohibited = ${JSON.stringify(constraints.prohibited_actions)};`);
      lines.push(`      expect(prohibited).toContain('${action}');`);
      lines.push(`    });`);
      testCount++;
    }
    lines.push(`  });`);
  }

  // 5. Escalation rule tests
  if (constraints?.escalation_rules?.length) {
    lines.push('');
    lines.push(`  describe('escalation rules', () => {`);
    for (const rule of constraints.escalation_rules) {
      lines.push(`    it('should escalate "${rule.condition}" to ${rule.escalate_to}', () => {`);
      lines.push(`      const escalation = ${JSON.stringify(rule)};`);
      lines.push(`      expect(escalation.condition).toBeDefined();`);
      lines.push(`      expect(escalation.escalate_to).toBeDefined();`);
      lines.push(`    });`);
      testCount++;
    }
    lines.push(`  });`);
  }

  // 6. Budget test
  if (constraints?.budget) {
    lines.push('');
    lines.push(`  describe('budget constraints', () => {`);
    lines.push(`    it('should enforce budget limit: ${constraints.budget.max_cost} ${constraints.budget.currency}', () => {`);
    lines.push(`      const budget = ${JSON.stringify(constraints.budget)};`);
    lines.push(`      expect(budget.max_cost).toBeGreaterThan(0);`);
    lines.push(`    });`);
    lines.push(`  });`);
    testCount++;
  }

  // Minimum test if no constraints
  if (testCount === 0) {
    lines.push('');
    lines.push(`  it('agent ${name} exists (no constraints defined)', () => {`);
    lines.push(`    expect(true).toBe(true);`);
    lines.push(`  });`);
    testCount = 1;
  }

  lines.push(`});`);
  lines.push('');

  return Object.freeze({
    filename: `${name}-compliance-tests.ts`,
    content: lines.join('\n'),
    testCount,
  });
};
