import type { PreHook } from '../../types.js';
import { isLLMMessageArray } from './extract-message-text.js';

const DISCLOSURE_TEXT = 'This response is generated by an AI system. Content should be verified by a human before use.';

/** OBL-015: Inject AI-generated disclosure into system prompt */
export const disclosureHook: PreHook = (ctx) => {
  const val = ctx.params['messages'];

  if (!isLLMMessageArray(val)) {
    return {
      ...ctx,
      params: {
        ...ctx.params,
        messages: [{ role: 'system', content: DISCLOSURE_TEXT }],
      },
      metadata: { ...ctx.metadata, disclosureInjected: true },
    };
  }

  const messages = val;
  const hasSystemMsg = messages.some((m) => m.role === 'system');

  if (hasSystemMsg) {
    return {
      ...ctx,
      params: {
        ...ctx.params,
        messages: messages.map((m) =>
          m.role === 'system'
            ? { ...m, content: `${m.content}\n\n${DISCLOSURE_TEXT}` }
            : m,
        ),
      },
      metadata: { ...ctx.metadata, disclosureInjected: true },
    };
  }

  return {
    ...ctx,
    params: {
      ...ctx.params,
      messages: [{ role: 'system', content: DISCLOSURE_TEXT }, ...messages],
    },
    metadata: { ...ctx.metadata, disclosureInjected: true },
  };
};
