({
  _escapeHtml: (str) => {
    if (str === null || str === undefined) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#x27;');
  },

  renderExecutiveSummary: function(orgName, summaryText, generatedAt) {
    const esc = this._escapeHtml;
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
      body{font-family:'Helvetica Neue',Arial,sans-serif;margin:40px;color:#1a1a2e;line-height:1.6;}
      h1{color:#0d47a1;border-bottom:2px solid #0d47a1;padding-bottom:8px;}
      h2{color:#1565c0;margin-top:24px;}
      .header{display:flex;justify-content:space-between;margin-bottom:24px;}
      .meta{color:#666;font-size:12px;}
      .content{white-space:pre-wrap;}
    </style></head><body>
    <div class="header"><h1>Executive Summary \u2014 AI Act Compliance</h1><div class="meta">Generated: ${esc(generatedAt)}<br>Organization: ${esc(orgName)}</div></div>
    <div class="content">${esc(summaryText)}</div>
    <div class="meta" style="margin-top:40px;border-top:1px solid #ddd;padding-top:8px;">Generated by Complior \u2014 AI Act Compliance Platform</div>
    </body></html>`;
  },

  renderObligationMatrix: function(orgName, matrixHtml, generatedAt) {
    const esc = this._escapeHtml;
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
      body{font-family:'Helvetica Neue',Arial,sans-serif;margin:40px;color:#1a1a2e;}
      h1{color:#0d47a1;border-bottom:2px solid #0d47a1;padding-bottom:8px;}
      .meta{color:#666;font-size:12px;}
      .legend{margin:16px 0;font-size:12px;}
      .legend span{margin-right:16px;}
    </style></head><body>
    <h1>Obligation Matrix \u2014 ${esc(orgName)}</h1>
    <div class="meta">Generated: ${esc(generatedAt)}</div>
    <div class="legend"><span style="color:#22c55e;font-weight:bold;">\u2713 Completed</span><span style="color:#eab308;font-weight:bold;">\u25D0 In Progress</span><span style="color:#ef4444;font-weight:bold;">\u2717 Pending</span><span style="color:#9ca3af;">\u2014 N/A</span></div>
    ${matrixHtml}
    <div class="meta" style="margin-top:40px;border-top:1px solid #ddd;padding-top:8px;">Generated by Complior \u2014 AI Act Compliance Platform</div>
    </body></html>`;
  },

  renderAIRegistry: function(orgName, tools, generatedAt) {
    const esc = this._escapeHtml;
    let rows = '';
    for (const tool of tools) {
      rows += `<tr>
        <td style="border:1px solid #ddd;padding:6px;">${esc(tool.name)}</td>
        <td style="border:1px solid #ddd;padding:6px;">${esc(tool.vendorName) || '\u2014'}</td>
        <td style="border:1px solid #ddd;padding:6px;">${esc(tool.purpose) || '\u2014'}</td>
        <td style="border:1px solid #ddd;padding:6px;">${esc(tool.riskLevel) || 'Unclassified'}</td>
        <td style="border:1px solid #ddd;padding:6px;">${esc(tool.complianceStatus) || 'not_started'}</td>
        <td style="border:1px solid #ddd;padding:6px;">${esc(tool.domain) || '\u2014'}</td>
      </tr>`;
    }
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
      body{font-family:'Helvetica Neue',Arial,sans-serif;margin:40px;color:#1a1a2e;line-height:1.6;}
      h1{color:#0d47a1;border-bottom:2px solid #0d47a1;padding-bottom:8px;}
      .meta{color:#666;font-size:12px;}
      table{width:100%;border-collapse:collapse;margin-top:16px;font-size:12px;}
      th{background:#f0f4f8;border:1px solid #ddd;padding:8px;text-align:left;}
    </style></head><body>
    <h1>AI System Registry \u2014 ${esc(orgName)}</h1>
    <div class="meta">Generated: ${esc(generatedAt)} | Total Systems: ${tools.length}</div>
    <table><thead><tr><th>System Name</th><th>Vendor</th><th>Purpose</th><th>Risk Level</th><th>Compliance</th><th>Domain</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <div class="meta" style="margin-top:40px;border-top:1px solid #ddd;padding-top:8px;">Generated by Complior \u2014 AI Act Compliance Platform</div>
    </body></html>`;
  },
})
