({
  render: (document, sections, organizationName) => {
    const escapeHtml = (str) => {
      if (!str) return '';
      return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
    };

    const title = escapeHtml(document.title || 'Compliance Document');
    const org = escapeHtml(organizationName || '');
    const date = new Date().toISOString().slice(0, 10);

    const sorted = [...sections].sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0));

    const sectionHtml = sorted.map((s) => {
      const sTitle = escapeHtml(s.title || s.sectionCode);
      const content = s.content && s.content.text ? s.content.text : '';
      const escaped = escapeHtml(content);
      const formatted = escaped.replace(/\n/g, '<br/>');

      return `    <div class="section">
      <h2>${sTitle}</h2>
      <p>${formatted}</p>
    </div>`;
    }).join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a1a;
      padding: 2cm;
    }
    .header {
      border-bottom: 3px solid #0d9488;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .header h1 {
      color: #0d9488;
      font-size: 20pt;
      margin-bottom: 4px;
    }
    .header .meta {
      color: #666;
      font-size: 9pt;
    }
    .section {
      margin-bottom: 20px;
      page-break-inside: avoid;
    }
    .section h2 {
      color: #0d9488;
      font-size: 13pt;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 4px;
      margin-bottom: 8px;
    }
    .section p {
      text-align: justify;
    }
    .footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #e5e7eb;
      font-size: 8pt;
      color: #999;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="meta">${org}${org ? ' — ' : ''}Generated: ${date}</div>
  </div>
${sectionHtml}
  <div class="footer">
    Generated by Complior AI Act Compliance Platform &mdash; complior.eu
  </div>
</body>
</html>`;
  },
})
