import type { MiddlewareConfig, PostHook } from '../types.js';
import { extractResponseText } from '../hooks/post/extract-response-text.js';

const DEFAULT_DISCLOSURE_TEXT = 'This content was generated by AI.';

/** Clone response with modified text content using type narrowing (no `as` assertions) */
const injectTextIntoResponse = (response: unknown, originalText: string, newText: string): unknown => {
  if (!response || typeof response !== 'object') return response;

  // OpenAI: { choices: [{ message: { content: string } }] }
  if ('choices' in response) {
    const choices = response.choices;
    if (Array.isArray(choices) && choices.length > 0) {
      const first: unknown = choices[0];
      if (first && typeof first === 'object' && 'message' in first) {
        const msg: unknown = first.message;
        if (msg && typeof msg === 'object' && 'content' in msg && msg.content === originalText) {
          return {
            ...response,
            choices: [
              { ...first, message: { ...msg, content: newText } },
              ...choices.slice(1),
            ],
          };
        }
      }
    }
  }

  // Anthropic: { content: [{ text: string }] }
  if ('content' in response) {
    const content = response.content;
    if (Array.isArray(content) && content.length > 0) {
      const first: unknown = content[0];
      if (first && typeof first === 'object' && 'text' in first && first.text === originalText) {
        return {
          ...response,
          content: [
            { ...first, text: newText },
            ...content.slice(1),
          ],
        };
      }
    }
  }

  return response;
};

/** OBL-015 Art.50(1): Inject AI disclosure into LLM response */
export const createDisclosureInjectorHook = (config: MiddlewareConfig): PostHook => {
  let callCount = 0;
  const text = config.disclosureText ?? DEFAULT_DISCLOSURE_TEXT;
  const position = config.disclosurePosition ?? 'append';
  const frequency = config.disclosureFrequency ?? 'every';

  return (ctx, response) => {
    if (config.disclosureInjection !== true) {
      return { response, metadata: ctx.metadata, headers: {} };
    }

    callCount++;

    if (frequency === 'session-start' && callCount > 1) {
      return { response, metadata: ctx.metadata, headers: {} };
    }

    // Header mode — don't modify response body
    if (position === 'header') {
      return {
        response,
        metadata: {
          ...ctx.metadata,
          disclosureResponseInjected: true,
          disclosurePosition: 'header',
        },
        headers: { 'X-AI-Disclosure-Text': text },
      };
    }

    // Prepend/append — clone response with modified text
    const originalText = extractResponseText(response);
    const newText = position === 'prepend'
      ? `${text}\n\n${originalText}`
      : `${originalText}\n\n${text}`;

    return {
      response: injectTextIntoResponse(response, originalText, newText),
      metadata: {
        ...ctx.metadata,
        disclosureResponseInjected: true,
        disclosurePosition: position,
      },
      headers: {},
    };
  };
};
