'use strict';

// Plan limits — single source of truth (Pricing v3.0)
// Used by: app/seeds/plans.js, SubscriptionLimitChecker (reads from DB after seed)
// To change limits: update here → re-seed or write migration UPDATE
// Convention: -1 = unlimited, 0 = blocked
// Prices in EUR cents. Frontend shows both EUR and USD ($49 / €49).
// Annual = 20% discount on monthly price.
// Trial: Free = no card, Starter/Growth/Scale = 14-day trial (card required).

const plans = [
  {
    name: 'free',
    displayName: 'Free',
    priceMonthly: 0,
    priceYearly: 0,
    trialDays: 0,
    cardRequired: false,
    maxTools: 1,
    maxUsers: 1,
    maxEmployees: 0,
    features: {
      quickCheck: true,
      eva: 0,
      newsletter: true,
      classification: 'basic',
      complianceTimeline: false,
    },
    active: true,
    sortOrder: 0,
  },
  {
    name: 'starter',
    displayName: 'Starter',
    priceMonthly: 4900,
    priceYearly: 47040,
    trialDays: 14,
    cardRequired: true,
    maxTools: 5,
    maxUsers: 2,
    maxEmployees: 15,
    features: {
      literacy: true,
      eva: 200,
      classification: 'full',
      complianceTimeline: true,
      csvImport: 'basic',
    },
    active: true,
    sortOrder: 1,
  },
  {
    name: 'growth',
    displayName: 'Growth',
    priceMonthly: 14900,
    priceYearly: 143040,
    trialDays: 14,
    cardRequired: true,
    maxTools: 20,
    maxUsers: 10,
    maxEmployees: 50,
    features: {
      literacy: true,
      fria: true,
      eva: 1000,
      gapAnalysis: true,
      siegel: true,
      documents: 'full',
      complianceTimeline: true,
      selfRegistration: true,
      csvImport: 'full',
      csvTools: true,
      badge: true,
    },
    active: true,
    sortOrder: 2,
  },
  {
    name: 'scale',
    displayName: 'Scale',
    priceMonthly: 39900,
    priceYearly: 383040,
    trialDays: 14,
    cardRequired: true,
    maxTools: -1,
    maxUsers: -1,
    maxEmployees: 250,
    features: {
      literacy: true,
      fria: true,
      eva: -1,
      gapAnalysis: true,
      autoDiscovery: true,
      api: true,
      monitoring: true,
      siegel: true,
      documents: 'full',
      complianceTimeline: true,
      selfRegistration: true,
      csvImport: 'full',
      csvTools: true,
      badge: true,
    },
    active: true,
    sortOrder: 3,
  },
  {
    name: 'enterprise',
    displayName: 'Enterprise',
    priceMonthly: -1,
    priceYearly: -1,
    trialDays: 0,
    cardRequired: false,
    maxTools: -1,
    maxUsers: -1,
    maxEmployees: -1,
    features: {
      all: true,
      eva: -1,
      onPremise: true,
      sla: true,
      whiteLabel: true,
      complianceTimeline: true,
      selfRegistration: true,
      csvImport: 'full',
      csvTools: true,
      badge: true,
      api: true,
    },
    active: true,
    sortOrder: 4,
  },
];

module.exports = plans;
