'use strict';

const catalog = [
  // ═══════════════════════════════════════════════════════════════════════════
  // CHATBOTS / LLMs (~30)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'ChatGPT',
    vendor: 'OpenAI',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'marketing', 'coding', 'education', 'other'],
    description: 'General-purpose conversational AI assistant for text' +
      ' generation, Q&A, coding, and analysis.',
    websiteUrl: 'https://chat.openai.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Claude',
    vendor: 'Anthropic',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'coding', 'analytics', 'other'],
    description: 'AI assistant focused on safety, helpfulness, and honesty' +
      ' for text generation and analysis.',
    websiteUrl: 'https://claude.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Gemini',
    vendor: 'Google',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'coding', 'analytics', 'other'],
    description: 'Multimodal AI model for text, image, and code' +
      ' understanding across Google products.',
    websiteUrl: 'https://gemini.google.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Le Chat (Mistral)',
    vendor: 'Mistral AI',
    vendorCountry: 'FR',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'coding', 'other'],
    description: 'EU-based conversational AI assistant built on open-weight' +
      ' Mistral models.',
    websiteUrl: 'https://chat.mistral.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Microsoft Copilot',
    vendor: 'Microsoft',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'coding', 'analytics', 'other'],
    description: 'AI assistant integrated into Microsoft 365 apps for' +
      ' productivity, search, and content generation.',
    websiteUrl: 'https://copilot.microsoft.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Perplexity AI',
    vendor: 'Perplexity AI',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'AI-powered search engine providing cited answers from web' +
      ' sources in real time.',
    websiteUrl: 'https://www.perplexity.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Llama',
    vendor: 'Meta',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Open-weight large language model family for research and' +
      ' commercial deployment.',
    websiteUrl: 'https://llama.meta.com',
    dataResidency: null,
    active: true,
  },
  {
    name: 'DeepSeek Chat',
    vendor: 'DeepSeek',
    vendorCountry: 'CN',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Chinese-developed AI chatbot with strong coding and' +
      ' reasoning capabilities.',
    websiteUrl: 'https://chat.deepseek.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Grok',
    vendor: 'xAI',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'analytics', 'other'],
    description: 'AI chatbot integrated with X/Twitter, focused on' +
      ' real-time information and humor.',
    websiteUrl: 'https://grok.x.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Pi',
    vendor: 'Inflection AI',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'other'],
    description: 'Personal AI companion designed for empathetic, supportive' +
      ' conversations.',
    websiteUrl: 'https://pi.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Cohere Command',
    vendor: 'Cohere',
    vendorCountry: 'CA',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'analytics', 'other'],
    description: 'Enterprise LLM platform for text generation, RAG, and' +
      ' classification with data privacy focus.',
    websiteUrl: 'https://cohere.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Aleph Alpha Luminous',
    vendor: 'Aleph Alpha',
    vendorCountry: 'DE',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'analytics', 'other'],
    description: 'EU-sovereign AI model for enterprise use with on-premise' +
      ' deployment and GDPR compliance.',
    websiteUrl: 'https://aleph-alpha.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'HuggingChat',
    vendor: 'Hugging Face',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'other'],
    description: 'Open-source chatbot interface powered by community models' +
      ' on Hugging Face.',
    websiteUrl: 'https://huggingface.co/chat',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'You.com',
    vendor: 'You.com',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'AI search engine with chat interface combining web search' +
      ' and AI generation.',
    websiteUrl: 'https://you.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Jasper Chat',
    vendor: 'Jasper AI',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI chat assistant focused on marketing content generation' +
      ' and brand voice.',
    websiteUrl: 'https://www.jasper.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Character.AI',
    vendor: 'Character Technologies',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['other'],
    description: 'Platform for creating and chatting with AI characters and' +
      ' personas.',
    websiteUrl: 'https://character.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Replika',
    vendor: 'Luka Inc.',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['other'],
    description: 'AI companion chatbot for personal conversations and' +
      ' emotional support.',
    websiteUrl: 'https://replika.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Poe',
    vendor: 'Quora',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['other'],
    description: 'Aggregator platform providing access to multiple AI' +
      ' chatbots from different providers.',
    websiteUrl: 'https://poe.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'ChatSonic',
    vendor: 'Writesonic',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'customer_service', 'other'],
    description: 'AI chatbot with real-time web search and image generation' +
      ' capabilities.',
    websiteUrl: 'https://writesonic.com/chat',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Ernie Bot',
    vendor: 'Baidu',
    vendorCountry: 'CN',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'other'],
    description: 'Chinese AI chatbot built on Baidu ERNIE large language' +
      ' model.',
    websiteUrl: 'https://yiyan.baidu.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Qwen Chat',
    vendor: 'Alibaba Cloud',
    vendorCountry: 'CN',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Multilingual AI assistant from Alibaba with strong' +
      ' multilingual and coding capabilities.',
    websiteUrl: 'https://qwen.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Reka Core',
    vendor: 'Reka AI',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'Multimodal AI model capable of understanding text,' +
      ' images, video, and audio.',
    websiteUrl: 'https://reka.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'AI21 Jamba',
    vendor: 'AI21 Labs',
    vendorCountry: 'IL',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'analytics', 'other'],
    description: 'Enterprise AI platform for text generation,' +
      ' summarization, and language tasks.',
    websiteUrl: 'https://www.ai21.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Neuroflash',
    vendor: 'neuroflash GmbH',
    vendorCountry: 'DE',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'German AI content platform with chatbot for marketing' +
      ' copy in German and English.',
    websiteUrl: 'https://neuroflash.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Bing Chat Enterprise',
    vendor: 'Microsoft',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'Enterprise version of Bing Chat with commercial data' +
      ' protection and no data leakage.',
    websiteUrl: 'https://www.microsoft.com/en-us/bing',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'WizardLM',
    vendor: 'Microsoft Research',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'other'],
    description: 'Open-source instruction-following LLM with strong coding' +
      ' and reasoning performance.',
    websiteUrl: 'https://github.com/nlpxucan/WizardLM',
    dataResidency: null,
    active: true,
  },
  {
    name: 'Falcon Chat',
    vendor: 'Technology Innovation Institute',
    vendorCountry: 'AE',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['other'],
    description: 'Open-source LLM from TII Abu Dhabi, available for' +
      ' commercial and research use.',
    websiteUrl: 'https://falconllm.tii.ae',
    dataResidency: null,
    active: true,
  },
  {
    name: 'Coral (Cohere)',
    vendor: 'Cohere',
    vendorCountry: 'CA',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'analytics', 'other'],
    description: 'Enterprise chat interface with RAG capabilities for' +
      ' grounded, cited responses.',
    websiteUrl: 'https://coral.cohere.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'SambaNova Cloud',
    vendor: 'SambaNova Systems',
    vendorCountry: 'US',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'Enterprise AI platform with ultra-fast inference for' +
      ' open-source LLMs.',
    websiteUrl: 'https://sambanova.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Maritaca AI (Sabia)',
    vendor: 'Maritaca AI',
    vendorCountry: 'BR',
    category: 'chatbot',
    defaultRiskLevel: 'limited',
    domains: ['customer_service', 'other'],
    description: 'Portuguese-language AI assistant optimized for Brazilian' +
      ' and Portuguese markets.',
    websiteUrl: 'https://maritaca.ai',
    dataResidency: 'global',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CODING ASSISTANTS (~20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'GitHub Copilot',
    vendor: 'GitHub (Microsoft)',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI pair programmer providing code completions and' +
      ' suggestions in IDEs.',
    websiteUrl: 'https://github.com/features/copilot',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Cursor',
    vendor: 'Anysphere',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI-native code editor with integrated chat, code' +
      ' generation, and codebase understanding.',
    websiteUrl: 'https://cursor.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Tabnine',
    vendor: 'Tabnine',
    vendorCountry: 'IL',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI code assistant with private model deployment for' +
      ' secure enterprise code completion.',
    websiteUrl: 'https://www.tabnine.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Amazon Q Developer',
    vendor: 'Amazon Web Services',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI coding assistant for AWS with code generation,' +
      ' debugging, and security scanning.',
    websiteUrl: 'https://aws.amazon.com/q/developer/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Replit Ghostwriter',
    vendor: 'Replit',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI coding assistant integrated into Replit online IDE for' +
      ' code generation and explanation.',
    websiteUrl: 'https://replit.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Codeium',
    vendor: 'Exafunction',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'Free AI code completion tool supporting 70+ languages' +
      ' across major IDEs.',
    websiteUrl: 'https://codeium.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Sourcegraph Cody',
    vendor: 'Sourcegraph',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI code assistant with full codebase context for code' +
      ' generation and understanding.',
    websiteUrl: 'https://sourcegraph.com/cody',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'JetBrains AI Assistant',
    vendor: 'JetBrains',
    vendorCountry: 'CZ',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI assistant integrated into JetBrains IDEs for code' +
      ' completion, refactoring, and chat.',
    websiteUrl: 'https://www.jetbrains.com/ai/',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Devin',
    vendor: 'Cognition Labs',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'Autonomous AI software engineer capable of planning,' +
      ' coding, and debugging full tasks.',
    websiteUrl: 'https://devin.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Claude Code',
    vendor: 'Anthropic',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'Agentic coding tool for terminal-based code generation,' +
      ' editing, and project management.',
    websiteUrl: 'https://docs.anthropic.com/en/docs/claude-code',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Windsurf (Codeium)',
    vendor: 'Exafunction',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI-native IDE with agentic coding flows and deep codebase' +
      ' understanding.',
    websiteUrl: 'https://codeium.com/windsurf',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Codestral',
    vendor: 'Mistral AI',
    vendorCountry: 'FR',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'EU-based code generation model supporting 80+ programming' +
      ' languages.',
    websiteUrl: 'https://mistral.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'CodeGPT',
    vendor: 'CodeGPT',
    vendorCountry: 'CL',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'VS Code extension connecting multiple AI providers for' +
      ' code assistance.',
    websiteUrl: 'https://codegpt.co',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Aider',
    vendor: 'Aider (open source)',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'Open-source terminal-based AI pair programming tool' +
      ' working with local git repos.',
    websiteUrl: 'https://aider.chat',
    dataResidency: null,
    active: true,
  },
  {
    name: 'Continue',
    vendor: 'Continue Dev',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'Open-source AI code assistant for VS Code and JetBrains' +
      ' with custom model support.',
    websiteUrl: 'https://continue.dev',
    dataResidency: null,
    active: true,
  },
  {
    name: 'Snyk Code AI',
    vendor: 'Snyk',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI-powered code security scanning to find and fix' +
      ' vulnerabilities in real time.',
    websiteUrl: 'https://snyk.io',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Blackbox AI',
    vendor: 'Blackbox AI',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI code generation and search tool for developers with' +
      ' multi-language support.',
    websiteUrl: 'https://www.blackbox.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Sweep AI',
    vendor: 'Sweep AI',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI junior developer that turns GitHub issues into pull' +
      ' requests automatically.',
    websiteUrl: 'https://sweep.dev',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Bito AI',
    vendor: 'Bito Inc.',
    vendorCountry: 'US',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI assistant for code review, documentation, and' +
      ' performance optimization in IDEs.',
    websiteUrl: 'https://bito.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Qodo (formerly CodiumAI)',
    vendor: 'Qodo',
    vendorCountry: 'IL',
    category: 'coding',
    defaultRiskLevel: 'minimal',
    domains: ['coding'],
    description: 'AI-powered test generation and code quality tool for' +
      ' developers.',
    websiteUrl: 'https://www.qodo.ai',
    dataResidency: 'global',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // RECRUITMENT / HR (~25)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'HireVue',
    vendor: 'HireVue',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment', 'biometrics'],
    description: 'AI-powered video interview platform with candidate' +
      ' assessment and game-based evaluations.',
    websiteUrl: 'https://www.hirevue.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Personio AI',
    vendor: 'Personio',
    vendorCountry: 'DE',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI features in German HR platform for automated' +
      ' screening, onboarding, and people analytics.',
    websiteUrl: 'https://www.personio.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Workday AI',
    vendor: 'Workday',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-enhanced HCM platform for talent acquisition,' +
      ' workforce planning, and employee insights.',
    websiteUrl: 'https://www.workday.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'SAP SuccessFactors AI',
    vendor: 'SAP',
    vendorCountry: 'DE',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-powered talent management in SAP HCM for recruiting,' +
      ' learning, and succession planning.',
    websiteUrl: 'https://www.sap.com/products/hcm.html',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Harver (formerly Pymetrics)',
    vendor: 'Harver',
    vendorCountry: 'NL',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment', 'biometrics'],
    description: 'AI hiring platform using neuroscience-based games and' +
      ' behavioral assessments for candidate matching.',
    websiteUrl: 'https://harver.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'HiPeople',
    vendor: 'HiPeople GmbH',
    vendorCountry: 'DE',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-powered talent assessment and reference checking' +
      ' platform for data-driven hiring.',
    websiteUrl: 'https://www.hipeople.io',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Textio',
    vendor: 'Textio',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI writing tool analyzing and optimizing job postings for' +
      ' inclusive language and effectiveness.',
    websiteUrl: 'https://textio.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Paradox (Olivia)',
    vendor: 'Paradox',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI recruiting assistant chatbot automating screening,' +
      ' scheduling, and candidate communication.',
    websiteUrl: 'https://www.paradox.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Eightfold AI',
    vendor: 'Eightfold AI',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI talent intelligence platform for sourcing, matching,' +
      ' and workforce planning.',
    websiteUrl: 'https://eightfold.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Beamery',
    vendor: 'Beamery',
    vendorCountry: 'GB',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-powered talent management platform for proactive' +
      ' recruiting and internal mobility.',
    websiteUrl: 'https://beamery.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'SmartRecruiters AI',
    vendor: 'SmartRecruiters',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI features in recruiting platform for candidate' +
      ' matching, screening, and hiring automation.',
    websiteUrl: 'https://www.smartrecruiters.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Greenhouse AI',
    vendor: 'Greenhouse Software',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-enhanced applicant tracking system with structured' +
      ' hiring and candidate scoring.',
    websiteUrl: 'https://www.greenhouse.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Phenom',
    vendor: 'Phenom People',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI talent experience platform for personalized career' +
      ' sites, chatbots, and talent CRM.',
    websiteUrl: 'https://www.phenom.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'SeekOut',
    vendor: 'SeekOut',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI talent search and diversity recruiting platform for' +
      ' sourcing passive candidates.',
    websiteUrl: 'https://seekout.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Fetcher',
    vendor: 'Fetcher',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI recruiting automation for sourcing candidates and' +
      ' personalized outreach at scale.',
    websiteUrl: 'https://fetcher.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Ideal',
    vendor: 'Ideal (Ceridian)',
    vendorCountry: 'CA',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-powered talent screening and shortlisting for' +
      ' high-volume recruiting.',
    websiteUrl: 'https://ideal.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Arya by Leoforce',
    vendor: 'Leoforce',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI sourcing platform that finds and ranks candidates from' +
      ' multiple channels.',
    websiteUrl: 'https://leoforce.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Humanly',
    vendor: 'Humanly',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI chatbot for screening, scheduling, and note-taking in' +
      ' the hiring process.',
    websiteUrl: 'https://humanly.io',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Wonderlic WonScore',
    vendor: 'Wonderlic',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-scored cognitive ability and personality assessments' +
      ' for pre-employment testing.',
    websiteUrl: 'https://wonderlic.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'AssessFirst',
    vendor: 'AssessFirst',
    vendorCountry: 'FR',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI predictive hiring platform using personality,' +
      ' motivation, and cognitive assessments.',
    websiteUrl: 'https://www.assessfirst.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Recruitee AI',
    vendor: 'Recruitee (Tellent)',
    vendorCountry: 'NL',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'EU-based collaborative hiring platform with AI-powered' +
      ' candidate matching and pipeline management.',
    websiteUrl: 'https://recruitee.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Lever AI',
    vendor: 'Lever (Employ)',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI-enhanced ATS and CRM for nurturing talent pipelines' +
      ' and data-driven hiring.',
    websiteUrl: 'https://www.lever.co',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'iCIMS AI',
    vendor: 'iCIMS',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'AI talent cloud with intelligent matching, chatbot, and' +
      ' candidate engagement automation.',
    websiteUrl: 'https://www.icims.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Cornerstone AI',
    vendor: 'Cornerstone OnDemand',
    vendorCountry: 'US',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment', 'education'],
    description: 'AI-powered talent management for learning, skills' +
      ' development, and workforce agility.',
    websiteUrl: 'https://www.cornerstoneondemand.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Softgarden AI',
    vendor: 'softgarden',
    vendorCountry: 'DE',
    category: 'recruitment',
    defaultRiskLevel: 'high',
    domains: ['employment'],
    description: 'German ATS with AI-powered job ad optimization and' +
      ' candidate matching for SMBs.',
    websiteUrl: 'https://www.softgarden.com',
    dataResidency: 'EU',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CUSTOMER SERVICE (~20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Zendesk AI',
    vendor: 'Zendesk',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI-powered customer service platform with automated' +
      ' ticket routing, bots, and agent assist.',
    websiteUrl: 'https://www.zendesk.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Salesforce Einstein',
    vendor: 'Salesforce',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service', 'analytics', 'marketing'],
    description: 'AI layer across Salesforce CRM for predictions,' +
      ' recommendations, and automated workflows.',
    websiteUrl: 'https://www.salesforce.com/einstein/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Intercom Fin',
    vendor: 'Intercom',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI customer service agent that resolves support queries' +
      ' using company knowledge base.',
    websiteUrl: 'https://www.intercom.com/fin',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Drift',
    vendor: 'Drift (Salesloft)',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service', 'marketing'],
    description: 'Conversational AI platform for B2B sales and marketing' +
      ' with chatbot and live chat.',
    websiteUrl: 'https://www.drift.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Freshdesk Freddy AI',
    vendor: 'Freshworks',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI assistant in Freshdesk for auto-resolving tickets,' +
      ' smart routing, and agent productivity.',
    websiteUrl: 'https://www.freshworks.com/freshdesk/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Ada',
    vendor: 'Ada Support',
    vendorCountry: 'CA',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI-powered customer service automation platform for' +
      ' personalized support at scale.',
    websiteUrl: 'https://www.ada.cx',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Ultimate.ai',
    vendor: 'Ultimate (Zendesk)',
    vendorCountry: 'FI',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'EU-based AI platform for customer service automation with' +
      ' multilingual support.',
    websiteUrl: 'https://www.ultimate.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Cognigy',
    vendor: 'Cognigy',
    vendorCountry: 'DE',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'German enterprise conversational AI platform for voice' +
      ' and chat customer service automation.',
    websiteUrl: 'https://www.cognigy.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Parloa',
    vendor: 'Parloa',
    vendorCountry: 'DE',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'German AI platform for automated phone and chat customer' +
      ' service with natural conversations.',
    websiteUrl: 'https://www.parloa.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'LivePerson',
    vendor: 'LivePerson',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'Conversational AI platform for messaging-based customer' +
      ' engagement and support.',
    websiteUrl: 'https://www.liveperson.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Tidio AI',
    vendor: 'Tidio',
    vendorCountry: 'PL',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'EU-based AI chatbot and live chat platform for SMB' +
      ' customer support and sales.',
    websiteUrl: 'https://www.tidio.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Kustomer AI',
    vendor: 'Kustomer (Meta)',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI-powered CRM for customer service with unified' +
      ' conversation timeline and automation.',
    websiteUrl: 'https://www.kustomer.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Dixa AI',
    vendor: 'Dixa',
    vendorCountry: 'DK',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'Danish conversational customer service platform with' +
      ' AI-powered routing and agent assist.',
    websiteUrl: 'https://www.dixa.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Forethought',
    vendor: 'Forethought',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI platform for customer support automating ticket' +
      ' triage, resolution, and agent assist.',
    websiteUrl: 'https://forethought.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Aisera',
    vendor: 'Aisera',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI service management platform for IT, HR, and customer' +
      ' service automation.',
    websiteUrl: 'https://aisera.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Boost.ai',
    vendor: 'Boost.ai',
    vendorCountry: 'NO',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'Nordic enterprise conversational AI platform for scalable' +
      ' virtual agent deployments.',
    websiteUrl: 'https://www.boost.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Certainly',
    vendor: 'Certainly',
    vendorCountry: 'DK',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'Danish conversational AI platform for e-commerce customer' +
      ' engagement and support.',
    websiteUrl: 'https://certainly.io',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Kommunicate',
    vendor: 'Kommunicate',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI chatbot and helpdesk platform for automating customer' +
      ' conversations across channels.',
    websiteUrl: 'https://www.kommunicate.io',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Moveworks',
    vendor: 'Moveworks',
    vendorCountry: 'US',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'AI platform automating IT and employee service requests' +
      ' through natural language.',
    websiteUrl: 'https://www.moveworks.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Solvemate (Dixa)',
    vendor: 'Dixa',
    vendorCountry: 'DE',
    category: 'customer_service',
    defaultRiskLevel: 'minimal',
    domains: ['customer_service'],
    description: 'German AI chatbot for customer service with contextual' +
      ' conversation flows and diagnostics.',
    websiteUrl: 'https://www.dixa.com/solvemate',
    dataResidency: 'EU',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MARKETING (~20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Jasper',
    vendor: 'Jasper AI',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI content creation platform for marketing teams with' +
      ' brand voice and campaign workflows.',
    websiteUrl: 'https://www.jasper.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Copy.ai',
    vendor: 'Copy.ai',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI-powered copywriting tool for marketing content, ads,' +
      ' social media, and email.',
    websiteUrl: 'https://www.copy.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Writesonic',
    vendor: 'Writesonic',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI writing platform for SEO-optimized blog posts, ads,' +
      ' and marketing copy.',
    websiteUrl: 'https://writesonic.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Phrasee',
    vendor: 'Phrasee (Jacquard)',
    vendorCountry: 'GB',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI-powered brand language optimization for email subject' +
      ' lines, push, and social copy.',
    websiteUrl: 'https://phrasee.co',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Persado',
    vendor: 'Persado',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'Motivation AI platform generating emotionally targeted' +
      ' marketing language at scale.',
    websiteUrl: 'https://www.persado.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Albert.ai',
    vendor: 'Albert Technologies (Zoomd)',
    vendorCountry: 'IL',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'Autonomous AI for digital marketing campaign execution' +
      ' across channels.',
    websiteUrl: 'https://albert.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Seventh Sense',
    vendor: 'Seventh Sense',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'AI send-time optimization for email marketing in HubSpot' +
      ' and Marketo.',
    websiteUrl: 'https://www.theseventhsense.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Crayon',
    vendor: 'Crayon',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'AI-powered competitive intelligence platform tracking' +
      ' market movements and competitor strategies.',
    websiteUrl: 'https://www.crayon.co',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Semrush AI',
    vendor: 'Semrush',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'AI-enhanced SEO and digital marketing toolkit for content' +
      ' optimization and competitive analysis.',
    websiteUrl: 'https://www.semrush.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'HubSpot AI',
    vendor: 'HubSpot',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'customer_service', 'analytics'],
    description: 'AI features across HubSpot CRM for content creation, lead' +
      ' scoring, and forecasting.',
    websiteUrl: 'https://www.hubspot.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Surfer SEO AI',
    vendor: 'Surfer',
    vendorCountry: 'PL',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'Polish AI-powered SEO tool for content optimization, SERP' +
      ' analysis, and article generation.',
    websiteUrl: 'https://surferseo.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Mailchimp AI',
    vendor: 'Mailchimp (Intuit)',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI features in email marketing platform for content' +
      ' generation, send optimization, and segmentation.',
    websiteUrl: 'https://mailchimp.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Optimizely AI',
    vendor: 'Optimizely',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'AI-powered digital experience platform for A/B testing,' +
      ' personalization, and content optimization.',
    websiteUrl: 'https://www.optimizely.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Drift Email',
    vendor: 'Drift (Salesloft)',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI-powered email marketing automation for B2B outreach' +
      ' and conversation routing.',
    websiteUrl: 'https://www.drift.com/platform/email/',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Anyword',
    vendor: 'Anyword',
    vendorCountry: 'IL',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI copywriting platform with predictive performance' +
      ' scoring for marketing content.',
    websiteUrl: 'https://anyword.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Brandwatch AI',
    vendor: 'Brandwatch (Cision)',
    vendorCountry: 'GB',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'AI social listening and consumer intelligence platform' +
      ' for brand monitoring and trend analysis.',
    websiteUrl: 'https://www.brandwatch.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Clearscope',
    vendor: 'Clearscope',
    vendorCountry: 'US',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI content optimization platform using NLP to improve' +
      ' search engine ranking performance.',
    websiteUrl: 'https://www.clearscope.io',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Smartly.io',
    vendor: 'Smartly',
    vendorCountry: 'FI',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'Finnish AI-powered ad tech platform for automated social' +
      ' advertising creative and optimization.',
    websiteUrl: 'https://www.smartly.io',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Adcreative.ai',
    vendor: 'AdCreative.ai',
    vendorCountry: 'FR',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing'],
    description: 'AI ad creative generation platform producing' +
      ' conversion-focused banner and social ad designs.',
    websiteUrl: 'https://www.adcreative.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'PathFactory',
    vendor: 'PathFactory',
    vendorCountry: 'CA',
    category: 'marketing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'analytics'],
    description: 'AI content intelligence platform tracking B2B buyer' +
      ' engagement and optimizing content journeys.',
    websiteUrl: 'https://www.pathfactory.com',
    dataResidency: 'global',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // WRITING / CONTENT (~15)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Grammarly',
    vendor: 'Grammarly',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI writing assistant for grammar, clarity, tone, and' +
      ' style improvements across platforms.',
    websiteUrl: 'https://www.grammarly.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'DeepL',
    vendor: 'DeepL SE',
    vendorCountry: 'DE',
    category: 'translation',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'EU-based AI translation service with superior quality for' +
      ' European languages and document translation.',
    websiteUrl: 'https://www.deepl.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Notion AI',
    vendor: 'Notion Labs',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI writing and summarization assistant built into Notion' +
      ' workspace for docs and wikis.',
    websiteUrl: 'https://www.notion.so/product/ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Tome',
    vendor: 'Tome',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'other'],
    description: 'AI-powered presentation and storytelling tool for' +
      ' creating visual narratives from text prompts.',
    websiteUrl: 'https://tome.app',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Beautiful.ai',
    vendor: 'Beautiful.ai',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI presentation software with smart templates that' +
      ' auto-adapt design and layout.',
    websiteUrl: 'https://www.beautiful.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Canva Magic Write',
    vendor: 'Canva',
    vendorCountry: 'AU',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'other'],
    description: 'AI text generation tool within Canva for creating copy,' +
      ' social posts, and document content.',
    websiteUrl: 'https://www.canva.com/magic-write/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'LanguageTool',
    vendor: 'LanguageTooler GmbH',
    vendorCountry: 'DE',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'German-based AI writing assistant for grammar, style, and' +
      ' spelling in 30+ languages.',
    websiteUrl: 'https://languagetool.org',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'QuillBot',
    vendor: 'QuillBot (Course Hero)',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI paraphrasing and writing tool for rewording,' +
      ' summarizing, and grammar checking.',
    websiteUrl: 'https://quillbot.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Wordtune',
    vendor: 'AI21 Labs',
    vendorCountry: 'IL',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI writing companion for rewriting, summarizing, and' +
      ' improving text clarity and tone.',
    websiteUrl: 'https://www.wordtune.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Otter.ai',
    vendor: 'Otter.ai',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI meeting transcription and note-taking tool with' +
      ' real-time captions and summaries.',
    websiteUrl: 'https://otter.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Fireflies.ai',
    vendor: 'Fireflies.ai',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI meeting assistant for transcription, summarization,' +
      ' and action item extraction.',
    websiteUrl: 'https://fireflies.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Textmetrics',
    vendor: 'Textmetrics',
    vendorCountry: 'NL',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['marketing', 'other'],
    description: 'Dutch AI writing tool for inclusive and SEO-optimized' +
      ' content with augmented writing.',
    websiteUrl: 'https://www.textmetrics.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Gamma',
    vendor: 'Gamma Tech',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI-powered tool for creating presentations, documents,' +
      ' and web pages from text prompts.',
    websiteUrl: 'https://gamma.app',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Coda AI',
    vendor: 'Coda',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI assistant in Coda docs for writing, summarizing, and' +
      ' automating document workflows.',
    websiteUrl: 'https://coda.io/product/ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Descript',
    vendor: 'Descript',
    vendorCountry: 'US',
    category: 'writing',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI-powered audio and video editor with transcription,' +
      ' filler word removal, and voice cloning.',
    websiteUrl: 'https://www.descript.com',
    dataResidency: 'US',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // IMAGE GENERATION / VIDEO (~20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Midjourney',
    vendor: 'Midjourney',
    vendorCountry: 'US',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI image generation tool creating high-quality artwork' +
      ' and visuals from text prompts.',
    websiteUrl: 'https://www.midjourney.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'DALL-E',
    vendor: 'OpenAI',
    vendorCountry: 'US',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI image generation model creating and editing images' +
      ' from natural language descriptions.',
    websiteUrl: 'https://openai.com/dall-e',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Stable Diffusion',
    vendor: 'Stability AI',
    vendorCountry: 'GB',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'Open-source AI image generation model for creating images' +
      ' locally or via cloud.',
    websiteUrl: 'https://stability.ai',
    dataResidency: null,
    active: true,
  },
  {
    name: 'Leonardo.ai',
    vendor: 'Leonardo.ai',
    vendorCountry: 'AU',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI image generation platform for game assets, marketing' +
      ' visuals, and creative content.',
    websiteUrl: 'https://leonardo.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Adobe Firefly',
    vendor: 'Adobe',
    vendorCountry: 'US',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI image generation trained on licensed content,' +
      ' integrated across Adobe Creative Cloud.',
    websiteUrl: 'https://www.adobe.com/products/firefly.html',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Canva Magic Design',
    vendor: 'Canva',
    vendorCountry: 'AU',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI design tools in Canva for generating images,' +
      ' presentations, and visual content.',
    websiteUrl: 'https://www.canva.com/magic-design/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Ideogram',
    vendor: 'Ideogram',
    vendorCountry: 'CA',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI image generator with strong typography rendering' +
      ' capabilities for text-in-image creation.',
    websiteUrl: 'https://ideogram.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Flux (Black Forest Labs)',
    vendor: 'Black Forest Labs',
    vendorCountry: 'DE',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'German AI image generation model with open weights and' +
      ' high-quality output.',
    websiteUrl: 'https://blackforestlabs.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Runway Gen-3',
    vendor: 'Runway',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI video generation and editing platform for creating' +
      ' video from text and image prompts.',
    websiteUrl: 'https://runwayml.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Synthesia',
    vendor: 'Synthesia',
    vendorCountry: 'GB',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'education', 'other'],
    description: 'AI video generation platform creating videos with' +
      ' realistic AI avatars from text scripts.',
    websiteUrl: 'https://www.synthesia.io',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'HeyGen',
    vendor: 'HeyGen',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI video creation platform with avatar presenters and' +
      ' multilingual voice cloning.',
    websiteUrl: 'https://www.heygen.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'D-ID',
    vendor: 'D-ID',
    vendorCountry: 'IL',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI video generation platform creating talking head videos' +
      ' from photos and text.',
    websiteUrl: 'https://www.d-id.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Lumen5',
    vendor: 'Lumen5',
    vendorCountry: 'CA',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI video creation tool that transforms blog posts and' +
      ' text into engaging social videos.',
    websiteUrl: 'https://lumen5.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Pictory',
    vendor: 'Pictory',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI video creation tool for turning long-form content into' +
      ' short branded videos.',
    websiteUrl: 'https://pictory.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'ElevenLabs',
    vendor: 'ElevenLabs',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['other'],
    description: 'AI voice synthesis platform for realistic text-to-speech,' +
      ' voice cloning, and dubbing.',
    websiteUrl: 'https://elevenlabs.io',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Sora',
    vendor: 'OpenAI',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI text-to-video model generating realistic and' +
      ' imaginative video scenes from text prompts.',
    websiteUrl: 'https://openai.com/sora',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Pika',
    vendor: 'Pika Labs',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI video generation and editing platform for creating' +
      ' short videos from text and images.',
    websiteUrl: 'https://pika.art',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Kling AI',
    vendor: 'Kuaishou',
    vendorCountry: 'CN',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'Chinese AI video generation model producing high-quality' +
      ' videos from text descriptions.',
    websiteUrl: 'https://klingai.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Murf.ai',
    vendor: 'Murf AI',
    vendorCountry: 'US',
    category: 'video',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'education', 'other'],
    description: 'AI voice generator for creating studio-quality voiceovers' +
      ' for videos and presentations.',
    websiteUrl: 'https://murf.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Clipdrop (Stability AI)',
    vendor: 'Stability AI',
    vendorCountry: 'GB',
    category: 'image_generation',
    defaultRiskLevel: 'limited',
    domains: ['marketing', 'other'],
    description: 'AI-powered creative tools for image generation,' +
      ' background removal, and enhancement.',
    websiteUrl: 'https://clipdrop.co',
    dataResidency: 'global',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ANALYTICS / BI (~15)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Tableau AI (Tableau Pulse)',
    vendor: 'Salesforce',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI-powered analytics in Tableau for automated insights,' +
      ' natural language queries, and data stories.',
    websiteUrl: 'https://www.tableau.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Power BI Copilot',
    vendor: 'Microsoft',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI assistant in Power BI for generating reports, DAX' +
      ' formulas, and data narratives.',
    websiteUrl: 'https://powerbi.microsoft.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'ThoughtSpot',
    vendor: 'ThoughtSpot',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI-powered analytics platform with natural language' +
      ' search and automated insights.',
    websiteUrl: 'https://www.thoughtspot.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Dataiku',
    vendor: 'Dataiku',
    vendorCountry: 'FR',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'French AI/ML platform for collaborative data science,' +
      ' MLOps, and analytics at enterprise scale.',
    websiteUrl: 'https://www.dataiku.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'H2O.ai',
    vendor: 'H2O.ai',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'Open-source AI/ML platform for automated machine learning' +
      ' and predictive analytics.',
    websiteUrl: 'https://h2o.ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'DataRobot',
    vendor: 'DataRobot',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'Enterprise AI platform for automated machine learning' +
      ' model building and deployment.',
    websiteUrl: 'https://www.datarobot.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Databricks AI',
    vendor: 'Databricks',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'Unified data analytics platform with AI/ML capabilities' +
      ' for lakehouse architecture.',
    websiteUrl: 'https://www.databricks.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Looker (Google)',
    vendor: 'Google',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI-enhanced business intelligence platform with natural' +
      ' language queries and smart suggestions.',
    websiteUrl: 'https://cloud.google.com/looker',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Qlik Sense AI',
    vendor: 'Qlik',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI-augmented analytics platform with associative engine' +
      ' and AI-generated insights.',
    websiteUrl: 'https://www.qlik.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Celonis AI',
    vendor: 'Celonis',
    vendorCountry: 'DE',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'German AI-powered process mining platform for analyzing' +
      ' and optimizing business processes.',
    websiteUrl: 'https://www.celonis.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Alteryx AI',
    vendor: 'Alteryx',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI-powered analytics automation platform for data' +
      ' preparation, blending, and predictive analytics.',
    websiteUrl: 'https://www.alteryx.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'SAS Viya AI',
    vendor: 'SAS Institute',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'Enterprise AI and analytics platform for advanced' +
      ' analytics, ML, and decision intelligence.',
    websiteUrl: 'https://www.sas.com/en_us/software/viya.html',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Snowflake Cortex',
    vendor: 'Snowflake',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'AI services within Snowflake data cloud for ML model' +
      ' serving and LLM-based data analysis.',
    websiteUrl: 'https://www.snowflake.com/en/data-cloud/cortex/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Palantir AIP',
    vendor: 'Palantir Technologies',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: null,
    domains: ['analytics', 'law_enforcement', 'other'],
    description: 'AI platform for operationalizing LLMs on enterprise data' +
      ' with ontology-driven decision making.',
    websiteUrl: 'https://www.palantir.com/platforms/aip/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Obviously AI',
    vendor: 'Obviously AI',
    vendorCountry: 'US',
    category: 'analytics',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'No-code AI platform for building and deploying predictive' +
      ' models from business data.',
    websiteUrl: 'https://www.obviously.ai',
    dataResidency: 'US',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MEDICAL (~10)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Ada Health',
    vendor: 'Ada Health GmbH',
    vendorCountry: 'DE',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services', 'other'],
    description: 'German AI-powered symptom assessment and health' +
      ' navigation platform for patients and providers.',
    websiteUrl: 'https://ada.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Doctolib AI',
    vendor: 'Doctolib',
    vendorCountry: 'FR',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'French healthcare platform with AI-powered appointment' +
      ' management and medical documentation.',
    websiteUrl: 'https://www.doctolib.fr',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Merative (ex-Watson Health)',
    vendor: 'Merative',
    vendorCountry: 'US',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI-powered clinical decision support and health data' +
      ' analytics platform (formerly IBM Watson Health).',
    websiteUrl: 'https://www.merative.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'PathAI',
    vendor: 'PathAI',
    vendorCountry: 'US',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services', 'biometrics'],
    description: 'AI-powered pathology platform for disease diagnosis from' +
      ' tissue sample analysis.',
    websiteUrl: 'https://www.pathai.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Babylon Health AI',
    vendor: 'eMed (formerly Babylon)',
    vendorCountry: 'GB',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI triage and symptom checker for remote patient' +
      ' consultation and health monitoring.',
    websiteUrl: 'https://www.emed.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Viz.ai',
    vendor: 'Viz.ai',
    vendorCountry: 'US',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI-powered medical imaging analysis for detecting stroke,' +
      ' pulmonary embolism, and cardiac events.',
    websiteUrl: 'https://www.viz.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Infermedica',
    vendor: 'Infermedica',
    vendorCountry: 'PL',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'Polish AI diagnostic engine for symptom assessment and' +
      ' patient triage in healthcare.',
    websiteUrl: 'https://infermedica.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Nuance DAX (Microsoft)',
    vendor: 'Microsoft (Nuance)',
    vendorCountry: 'US',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI clinical documentation assistant that automatically' +
      ' generates medical notes from conversations.',
    websiteUrl:
      'https://www.nuance.com/healthcare/ambient-clinical-intelligence.html',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Aidoc',
    vendor: 'Aidoc',
    vendorCountry: 'IL',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI radiology platform for detecting critical findings in' +
      ' medical imaging scans.',
    websiteUrl: 'https://www.aidoc.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Abridge',
    vendor: 'Abridge',
    vendorCountry: 'US',
    category: 'medical',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI medical conversation summarization turning' +
      ' doctor-patient dialogues into clinical notes.',
    websiteUrl: 'https://www.abridge.com',
    dataResidency: 'US',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEGAL (~10)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Harvey AI',
    vendor: 'Harvey AI',
    vendorCountry: 'US',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI platform for legal work including research, drafting,' +
      ' and document analysis for law firms.',
    websiteUrl: 'https://www.harvey.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Luminance',
    vendor: 'Luminance',
    vendorCountry: 'GB',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI-powered legal intelligence platform for contract' +
      ' review, negotiation, and due diligence.',
    websiteUrl: 'https://www.luminance.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Kira Systems',
    vendor: 'Kira Systems (Litera)',
    vendorCountry: 'CA',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI contract analysis and review tool for extracting' +
      ' clauses and provisions from documents.',
    websiteUrl: 'https://kirasystems.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Relativity Trace',
    vendor: 'Relativity',
    vendorCountry: 'US',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI-powered compliance and e-discovery platform for' +
      ' proactive communication surveillance.',
    websiteUrl: 'https://www.relativity.com/trace/',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'CoCounsel (Thomson Reuters)',
    vendor: 'Thomson Reuters',
    vendorCountry: 'CA',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI legal assistant for research, document review,' +
      ' contract analysis, and legal drafting.',
    websiteUrl: 'https://legal.thomsonreuters.com/en/products/cocounsel',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Casetext (CoCounsel)',
    vendor: 'Casetext (Thomson Reuters)',
    vendorCountry: 'US',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI legal research platform with case law search and brief' +
      ' analysis capabilities.',
    websiteUrl: 'https://casetext.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Lexis+ AI',
    vendor: 'LexisNexis (RELX)',
    vendorCountry: 'US',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI-powered legal research assistant with' +
      ' hallucination-checked citations and document drafting.',
    websiteUrl: 'https://www.lexisnexis.com/en-us/products/lexis-plus-ai.page',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Robin AI',
    vendor: 'Robin AI',
    vendorCountry: 'GB',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI contract drafting and review platform for legal teams' +
      ' to accelerate contract workflows.',
    websiteUrl: 'https://www.robinai.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Legal Robot',
    vendor: 'Legal Robot',
    vendorCountry: 'US',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['justice', 'other'],
    description: 'AI platform for legal language simplification and' +
      ' automated contract compliance analysis.',
    websiteUrl: 'https://legalrobot.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Juro AI',
    vendor: 'Juro',
    vendorCountry: 'GB',
    category: 'legal',
    defaultRiskLevel: null,
    domains: ['other'],
    description: 'AI contract management platform for automated drafting,' +
      ' review, and lifecycle management.',
    websiteUrl: 'https://juro.com',
    dataResidency: 'EU',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FINANCE (~10)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Bloomberg GPT',
    vendor: 'Bloomberg',
    vendorCountry: 'US',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'Finance-specific LLM trained on Bloomberg financial data' +
      ' for market analysis and insights.',
    websiteUrl: 'https://www.bloomberg.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Kensho',
    vendor: 'Kensho (S&P Global)',
    vendorCountry: 'US',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'AI analytics platform for financial data processing, NLP,' +
      ' and market intelligence.',
    websiteUrl: 'https://www.kensho.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Ayasdi (SymphonyAI)',
    vendor: 'SymphonyAI',
    vendorCountry: 'US',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'AI platform for financial crime detection, anti-money' +
      ' laundering, and fraud prevention.',
    websiteUrl: 'https://www.symphonyai.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Zest AI',
    vendor: 'Zest AI',
    vendorCountry: 'US',
    category: 'finance',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI-powered credit underwriting platform for fairer and' +
      ' more accurate lending decisions.',
    websiteUrl: 'https://www.zest.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Upstart',
    vendor: 'Upstart',
    vendorCountry: 'US',
    category: 'finance',
    defaultRiskLevel: 'high',
    domains: ['essential_services'],
    description: 'AI lending platform using ML for credit risk assessment' +
      ' beyond traditional FICO scores.',
    websiteUrl: 'https://www.upstart.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Planhat AI',
    vendor: 'Planhat',
    vendorCountry: 'SE',
    category: 'finance',
    defaultRiskLevel: 'minimal',
    domains: ['analytics'],
    description: 'Swedish AI-powered customer success platform with' +
      ' predictive churn and revenue analytics.',
    websiteUrl: 'https://www.planhat.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Quantexa',
    vendor: 'Quantexa',
    vendorCountry: 'GB',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'AI-powered decision intelligence for financial crime,' +
      ' fraud detection, and KYC/AML.',
    websiteUrl: 'https://www.quantexa.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Featurespace',
    vendor: 'Featurespace',
    vendorCountry: 'GB',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'AI fraud prevention platform using adaptive behavioral' +
      ' analytics for payment protection.',
    websiteUrl: 'https://www.featurespace.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Personetics',
    vendor: 'Personetics',
    vendorCountry: 'IL',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'AI platform for banking personalization, financial' +
      ' insights, and automated money management.',
    websiteUrl: 'https://personetics.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Temenos AI',
    vendor: 'Temenos',
    vendorCountry: 'CH',
    category: 'finance',
    defaultRiskLevel: null,
    domains: ['essential_services', 'analytics'],
    description: 'Swiss banking software with AI for credit scoring,' +
      ' compliance, and customer engagement.',
    websiteUrl: 'https://www.temenos.com',
    dataResidency: 'global',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EDUCATION (~10)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Duolingo Max',
    vendor: 'Duolingo',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI-enhanced language learning with GPT-4 powered roleplay' +
      ' and explanation features.',
    websiteUrl: 'https://www.duolingo.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Khanmigo',
    vendor: 'Khan Academy',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI tutoring assistant by Khan Academy providing' +
      ' personalized guidance and Socratic tutoring.',
    websiteUrl: 'https://www.khanacademy.org/khan-labs',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Photomath',
    vendor: 'Photomath (Google)',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI math problem solver using camera recognition with' +
      ' step-by-step explanations.',
    websiteUrl: 'https://photomath.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Quizlet Q-Chat',
    vendor: 'Quizlet',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI tutor chatbot for personalized study sessions and' +
      ' adaptive learning on Quizlet.',
    websiteUrl: 'https://quizlet.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Turnitin AI Detection',
    vendor: 'Turnitin',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI writing detection tool for academic integrity checking' +
      ' student submissions.',
    websiteUrl: 'https://www.turnitin.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Century Tech',
    vendor: 'Century Tech',
    vendorCountry: 'GB',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'UK-based AI learning platform providing personalized' +
      ' learning paths and teacher analytics.',
    websiteUrl: 'https://www.century.tech',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Gradescope',
    vendor: 'Gradescope (Turnitin)',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI-assisted grading platform for homework, exams, and' +
      ' assignments in higher education.',
    websiteUrl: 'https://www.gradescope.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Cognii',
    vendor: 'Cognii',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI virtual tutor for open-response assessment and' +
      ' personalized learning conversations.',
    websiteUrl: 'https://www.cognii.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Brainly AI',
    vendor: 'Brainly',
    vendorCountry: 'PL',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'Polish AI-powered learning community with step-by-step' +
      ' homework help and tutoring.',
    websiteUrl: 'https://brainly.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Querium',
    vendor: 'Querium',
    vendorCountry: 'US',
    category: 'education',
    defaultRiskLevel: 'high',
    domains: ['education'],
    description: 'AI STEM tutoring platform with step-by-step problem' +
      ' solving and diagnostic assessments.',
    websiteUrl: 'https://www.querium.com',
    dataResidency: 'US',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRANSLATION (~5)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Google Translate AI',
    vendor: 'Google',
    vendorCountry: 'US',
    category: 'translation',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI-powered translation service supporting 130+ languages' +
      ' with neural machine translation.',
    websiteUrl: 'https://translate.google.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Translated (ModernMT)',
    vendor: 'Translated',
    vendorCountry: 'IT',
    category: 'translation',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'Italian AI translation platform with adaptive neural' +
      ' machine translation for enterprise.',
    websiteUrl: 'https://translated.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Smartcat AI',
    vendor: 'Smartcat',
    vendorCountry: 'US',
    category: 'translation',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI translation management platform combining machine' +
      ' translation with human review workflows.',
    websiteUrl: 'https://www.smartcat.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Phrase AI',
    vendor: 'Phrase (Memsource)',
    vendorCountry: 'DE',
    category: 'translation',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'German AI-powered translation management platform with' +
      ' quality estimation and automation.',
    websiteUrl: 'https://phrase.com',
    dataResidency: 'EU',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OTHER / VERTICAL AI (~15)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'UiPath AI',
    vendor: 'UiPath',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['analytics', 'other'],
    description: 'AI-powered robotic process automation platform for' +
      ' automating business workflows.',
    websiteUrl: 'https://www.uipath.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Automation Anywhere',
    vendor: 'Automation Anywhere',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['analytics', 'other'],
    description: 'Intelligent automation platform combining RPA with AI for' +
      ' end-to-end business process automation.',
    websiteUrl: 'https://www.automationanywhere.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Zapier AI',
    vendor: 'Zapier',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI-enhanced workflow automation platform connecting 6000+' +
      ' apps with natural language setup.',
    websiteUrl: 'https://zapier.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Make (Integromat) AI',
    vendor: 'Make (Celonis)',
    vendorCountry: 'CZ',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'Czech visual workflow automation platform with AI modules' +
      ' for integration and process automation.',
    websiteUrl: 'https://www.make.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'n8n AI',
    vendor: 'n8n GmbH',
    vendorCountry: 'DE',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'German open-source workflow automation platform with AI' +
      ' agent and LLM integration nodes.',
    websiteUrl: 'https://n8n.io',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Weights & Biases',
    vendor: 'Weights & Biases',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['analytics', 'other'],
    description: 'MLOps platform for experiment tracking, model versioning,' +
      ' and ML pipeline management.',
    websiteUrl: 'https://wandb.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Hugging Face',
    vendor: 'Hugging Face',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: null,
    domains: ['coding', 'analytics', 'other'],
    description: 'AI model hub and platform for sharing, deploying, and' +
      ' collaborating on ML models.',
    websiteUrl: 'https://huggingface.co',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Notion Calendar AI (Clockwise)',
    vendor: 'Notion Labs',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI calendar optimization tool for intelligent scheduling' +
      ' and focus time management.',
    websiteUrl: 'https://www.notion.so/product/calendar',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Reclaim.ai',
    vendor: 'Reclaim AI',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI scheduling assistant that auto-schedules tasks,' +
      ' habits, and meetings in Google Calendar.',
    websiteUrl: 'https://reclaim.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Krisp',
    vendor: 'Krisp Technologies',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI noise cancellation and meeting transcription tool for' +
      ' clear audio in virtual meetings.',
    websiteUrl: 'https://krisp.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Scale AI',
    vendor: 'Scale AI',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: null,
    domains: ['analytics', 'other'],
    description: 'AI data labeling and model evaluation platform for' +
      ' training and improving AI systems.',
    websiteUrl: 'https://scale.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Pinecone',
    vendor: 'Pinecone',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['analytics', 'other'],
    description: 'Vector database for AI applications enabling semantic' +
      ' search and retrieval-augmented generation.',
    websiteUrl: 'https://www.pinecone.io',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Weaviate',
    vendor: 'Weaviate',
    vendorCountry: 'NL',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['analytics', 'other'],
    description: 'Dutch open-source vector database for AI-native search' +
      ' and RAG applications.',
    websiteUrl: 'https://weaviate.io',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Qdrant',
    vendor: 'Qdrant',
    vendorCountry: 'DE',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['analytics', 'other'],
    description: 'German open-source vector search engine for AI and ML' +
      ' applications with filtering.',
    websiteUrl: 'https://qdrant.tech',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Deepgram',
    vendor: 'Deepgram',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI speech-to-text and text-to-speech platform with' +
      ' real-time transcription API.',
    websiteUrl: 'https://deepgram.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'AssemblyAI',
    vendor: 'AssemblyAI',
    vendorCountry: 'US',
    category: 'other',
    defaultRiskLevel: 'minimal',
    domains: ['other'],
    description: 'AI speech-to-text API with speaker diarization, sentiment' +
      ' analysis, and content moderation.',
    websiteUrl: 'https://www.assemblyai.com',
    dataResidency: 'US',
    active: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // API PLATFORMS (~20) — for provider-lite and developer deployers
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'OpenAI API',
    vendor: 'OpenAI',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'customer_service', 'analytics', 'other'],
    description: 'API platform for GPT models — text generation, embeddings,' +
      ' vision, and function calling for application integration.',
    websiteUrl: 'https://platform.openai.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Anthropic Claude API',
    vendor: 'Anthropic',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'customer_service', 'other'],
    description: 'API for Claude models with tool use, vision, and extended' +
      ' context for building AI-powered applications.',
    websiteUrl: 'https://docs.anthropic.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Google Vertex AI',
    vendor: 'Google Cloud',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Google Cloud ML platform with Gemini models, AutoML,' +
      ' embeddings, and enterprise AI deployment tools.',
    websiteUrl: 'https://cloud.google.com/vertex-ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Azure OpenAI Service',
    vendor: 'Microsoft',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'customer_service', 'analytics', 'other'],
    description: 'Enterprise API for OpenAI models (GPT, DALL-E, Whisper)' +
      ' hosted on Azure with EU region options.',
    websiteUrl: 'https://azure.microsoft.com/products/ai-services/openai-service',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'AWS Bedrock',
    vendor: 'Amazon Web Services',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'customer_service', 'other'],
    description: 'Managed service for foundation models (Claude, Llama, Titan)' +
      ' with fine-tuning and RAG on AWS infrastructure.',
    websiteUrl: 'https://aws.amazon.com/bedrock',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Hugging Face Inference API',
    vendor: 'Hugging Face',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'API for 200K+ open-source models — NLP, vision, audio.' +
      ' Inference Endpoints for dedicated hosting.',
    websiteUrl: 'https://huggingface.co/inference-api',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Cohere API',
    vendor: 'Cohere',
    vendorCountry: 'CA',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'customer_service', 'other'],
    description: 'Enterprise NLP API with Command models for text generation,' +
      ' embeddings, reranking, and RAG workflows.',
    websiteUrl: 'https://cohere.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Mistral AI API (La Plateforme)',
    vendor: 'Mistral AI',
    vendorCountry: 'FR',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'customer_service', 'other'],
    description: 'EU-based API for Mistral models (Small, Medium, Large)' +
      ' with function calling and JSON mode. EU data residency.',
    websiteUrl: 'https://console.mistral.ai',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Replicate',
    vendor: 'Replicate',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['image_generation', 'coding', 'other'],
    description: 'Cloud API for running open-source ML models (Stable Diffusion,' +
      ' Llama, Whisper) with pay-per-use pricing.',
    websiteUrl: 'https://replicate.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Together AI',
    vendor: 'Together AI',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Fast inference API for open-source LLMs (Llama, Mixtral)' +
      ' with fine-tuning and dedicated endpoints.',
    websiteUrl: 'https://www.together.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Groq Cloud',
    vendor: 'Groq',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Ultra-fast inference API for open-source LLMs on custom' +
      ' LPU hardware. Low-latency model serving.',
    websiteUrl: 'https://groq.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Fireworks AI',
    vendor: 'Fireworks AI',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Fast inference platform for open-source and fine-tuned LLMs' +
      ' with function calling and structured output.',
    websiteUrl: 'https://fireworks.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Perplexity API (Sonar)',
    vendor: 'Perplexity AI',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'Search-augmented AI API for grounded answers with web' +
      ' citations. Sonar models for real-time information.',
    websiteUrl: 'https://docs.perplexity.ai',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'AI21 Labs API',
    vendor: 'AI21 Labs',
    vendorCountry: 'IL',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'marketing', 'other'],
    description: 'API for Jamba models — text generation, summarization,' +
      ' and paraphrasing for enterprise applications.',
    websiteUrl: 'https://www.ai21.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'Aleph Alpha API',
    vendor: 'Aleph Alpha',
    vendorCountry: 'DE',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'German sovereign AI platform with Luminous models.' +
      ' EU data residency, GDPR-compliant, on-premise option.',
    websiteUrl: 'https://www.aleph-alpha.com',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Anyscale (Ray Serve)',
    vendor: 'Anyscale',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Managed platform for deploying and scaling open-source LLMs' +
      ' using Ray distributed compute framework.',
    websiteUrl: 'https://www.anyscale.com',
    dataResidency: 'US',
    active: true,
  },
  {
    name: 'Databricks Model Serving',
    vendor: 'Databricks',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['analytics', 'other'],
    description: 'Enterprise ML platform with foundation model APIs, fine-tuning,' +
      ' and managed model serving on Databricks Lakehouse.',
    websiteUrl: 'https://www.databricks.com',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'OVHcloud AI Endpoints',
    vendor: 'OVHcloud',
    vendorCountry: 'FR',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'French cloud AI inference API with Mistral, Llama, and other' +
      ' open-source models. EU sovereign cloud.',
    websiteUrl: 'https://www.ovhcloud.com/en/public-cloud/ai-endpoints',
    dataResidency: 'EU',
    active: true,
  },
  {
    name: 'Cloudflare Workers AI',
    vendor: 'Cloudflare',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Edge AI inference for open-source models running on' +
      ' Cloudflare global network with serverless pricing.',
    websiteUrl: 'https://developers.cloudflare.com/workers-ai',
    dataResidency: 'global',
    active: true,
  },
  {
    name: 'DeepInfra',
    vendor: 'DeepInfra',
    vendorCountry: 'US',
    category: 'api_platform',
    defaultRiskLevel: 'limited',
    domains: ['coding', 'analytics', 'other'],
    description: 'Low-cost inference API for open-source LLMs with' +
      ' OpenAI-compatible endpoints and pay-per-token pricing.',
    websiteUrl: 'https://deepinfra.com',
    dataResidency: 'US',
    active: true,
  },
];

module.exports = catalog;
