'use strict';

const plans = [
  {
    name: 'free',
    displayName: 'Free',
    priceMonthly: 0,
    priceYearly: 0,
    maxTools: 0,
    maxUsers: 1,
    maxEmployees: 0,
    features: { quickCheck: true, eva: 3, newsletter: true },
    active: true,
    sortOrder: 0,
  },
  {
    name: 'starter',
    displayName: 'Starter',
    priceMonthly: 4900,
    priceYearly: 46800,
    maxTools: 1,
    maxUsers: 2,
    maxEmployees: 10,
    features: { literacy: true, eva: 10, classification: 'full' },
    active: true,
    sortOrder: 1,
  },
  {
    name: 'growth',
    displayName: 'Growth',
    priceMonthly: 14900,
    priceYearly: 142800,
    maxTools: 10,
    maxUsers: 5,
    maxEmployees: 50,
    features: {
      literacy: true,
      fria: true,
      eva: 50,
      gapAnalysis: true,
      siegel: true,
      documents: 'full',
    },
    active: true,
    sortOrder: 2,
  },
  {
    name: 'scale',
    displayName: 'Scale',
    priceMonthly: 39900,
    priceYearly: 382800,
    maxTools: 50,
    maxUsers: 20,
    maxEmployees: 200,
    features: {
      literacy: true,
      fria: true,
      eva: -1,
      gapAnalysis: true,
      autoDiscovery: true,
      api: true,
      monitoring: true,
      siegel: true,
      documents: 'full',
    },
    active: true,
    sortOrder: 3,
  },
  {
    name: 'enterprise',
    displayName: 'Enterprise',
    priceMonthly: -1,
    priceYearly: -1,
    maxTools: -1,
    maxUsers: -1,
    maxEmployees: -1,
    features: {
      all: true,
      onPremise: true,
      sla: true,
      whiteLabel: true,
    },
    active: true,
    sortOrder: 4,
  },
];

module.exports = plans;
