import { describe, it, expect } from 'vitest';
import { disclosureVerifyHook } from '../hooks/post/disclosure-verify.js';
import { contentMarkingHook } from '../hooks/post/content-marking.js';
import { escalationHook } from '../hooks/post/escalation.js';
import { headersHook } from '../hooks/post/headers.js';
import { biasCheckHook } from '../hooks/post/bias-check.js';
import { DisclosureMissingError } from '../errors.js';
import type { MiddlewareContext, MiddlewareConfig } from '../types.js';

const makeCtx = (metadata: Record<string, unknown> = {}, configOverrides: Partial<MiddlewareConfig> = {}): MiddlewareContext => ({
  provider: 'openai',
  method: 'create',
  config: { jurisdictions: ['EU'], ...configOverrides },
  params: {},
  metadata,
});

const openaiResponse = (content: string) => ({
  choices: [{ message: { content } }],
});

const anthropicResponse = (text: string) => ({
  content: [{ text }],
});

describe('post-hooks', () => {
  // ── disclosureVerifyHook ────────────────────────────────────────

  describe('disclosureVerifyHook', () => {
    // EN detection
    it('detects "AI-generated" in English response', () => {
      const response = openaiResponse('This is AI-generated content for your review.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
      expect((result.metadata['disclosureLanguagesFound'] as string[]).includes('EN')).toBe(true);
    });

    it('detects "artificial intelligence" in English response', () => {
      const response = openaiResponse('Powered by artificial intelligence technology.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    it('detects "generated by AI" in English response', () => {
      const response = openaiResponse('This text was generated by an AI model.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    // DE detection
    it('detects "KI-generiert" in German response', () => {
      const response = openaiResponse('Dies ist ein KI-generiert Inhalt.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
      expect((result.metadata['disclosureLanguagesFound'] as string[]).includes('DE')).toBe(true);
    });

    it('detects "künstliche Intelligenz" in German response', () => {
      const response = openaiResponse('Erstellt mit künstliche Intelligenz.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    // FR detection
    it('detects "intelligence artificielle" in French response', () => {
      const response = openaiResponse("Utilisant l'intelligence artificielle.");
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
      expect((result.metadata['disclosureLanguagesFound'] as string[]).includes('FR')).toBe(true);
    });

    it('detects "généré par l\'IA" in French response', () => {
      const response = openaiResponse("Ce contenu est généré par l'IA.");
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    // ES detection
    it('detects "generado por IA" in Spanish response', () => {
      const response = openaiResponse('Este contenido fue generado por IA.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
      expect((result.metadata['disclosureLanguagesFound'] as string[]).includes('ES')).toBe(true);
    });

    it('detects "inteligencia artificial" in Spanish response', () => {
      const response = openaiResponse('Creado con inteligencia artificial.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    // Provider format handling
    it('extracts text from OpenAI response format', () => {
      const response = openaiResponse('This is an AI system response.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    it('extracts text from Anthropic response format', () => {
      const response = anthropicResponse('This is an AI system response.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    // Missing disclosure
    it('sets disclosureVerified to false when no disclosure found', () => {
      const response = openaiResponse('Here is a simple weather forecast for today.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(false);
      expect((result.metadata['disclosureMissingLanguages'] as string[]).length).toBe(4);
    });

    // Block mode
    it('throws DisclosureMissingError in block mode when no disclosure found', () => {
      const ctx = makeCtx({}, { disclosureMode: 'block' });
      const response = openaiResponse('Just a plain response with no markers.');
      expect(() => disclosureVerifyHook(ctx, response)).toThrow(DisclosureMissingError);
    });

    // Warn-only mode
    it('does not throw in warn-only mode, sets metadata only', () => {
      const ctx = makeCtx({}, { disclosureMode: 'warn-only' });
      const response = openaiResponse('No disclosure here.');
      const result = disclosureVerifyHook(ctx, response);
      expect(result.metadata['disclosureVerified']).toBe(false);
    });

    // Custom phrases
    it('matches custom disclosure phrases', () => {
      const ctx = makeCtx({}, { customDisclosurePhrases: [/bot-produced/i] });
      const response = openaiResponse('This is bot-produced content.');
      const result = disclosureVerifyHook(ctx, response);
      expect(result.metadata['disclosureVerified']).toBe(true);
    });

    // Language filter
    it('only checks configured languages', () => {
      const ctx = makeCtx({}, { disclosureLanguages: ['DE'] });
      const response = openaiResponse('This is AI-generated content.'); // EN only
      const result = disclosureVerifyHook(ctx, response);
      expect(result.metadata['disclosureVerified']).toBe(false);
      expect(result.metadata['disclosureLanguagesChecked']).toEqual(['DE']);
    });

    it('finds disclosure when filtered language matches', () => {
      const ctx = makeCtx({}, { disclosureLanguages: ['EN'] });
      const response = openaiResponse('This is AI-generated content.');
      const result = disclosureVerifyHook(ctx, response);
      expect(result.metadata['disclosureVerified']).toBe(true);
      expect(result.metadata['disclosureLanguagesChecked']).toEqual(['EN']);
    });

    // Multiple languages in single response
    it('detects multiple languages in a single response', () => {
      const response = openaiResponse('AI-generated content. Erstellt mit künstliche Intelligenz.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.metadata['disclosureVerified']).toBe(true);
      const found = result.metadata['disclosureLanguagesFound'] as string[];
      expect(found.includes('EN')).toBe(true);
      expect(found.includes('DE')).toBe(true);
    });

    // Empty response
    it('handles empty response gracefully', () => {
      const result = disclosureVerifyHook(makeCtx(), null);
      expect(result.metadata['disclosureVerified']).toBe(false);
    });

    // Header values
    it('sets X-AI-Disclosure header to "verified" when disclosure found', () => {
      const response = openaiResponse('This is AI-generated content.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.headers['X-AI-Disclosure']).toBe('verified');
    });

    it('sets X-AI-Disclosure header to "missing" when no disclosure found', () => {
      const response = openaiResponse('Plain text response.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.headers['X-AI-Disclosure']).toBe('missing');
    });

    it('passes through the response object unchanged', () => {
      const response = openaiResponse('AI-generated test.');
      const result = disclosureVerifyHook(makeCtx(), response);
      expect(result.response).toBe(response);
    });
  });

  // ── contentMarkingHook ──────────────────────────────────────────

  describe('contentMarkingHook', () => {
    it('adds C2PA metadata with producer, timestamp, and provider', () => {
      const ctx = makeCtx();
      const result = contentMarkingHook(ctx, {});
      const c2pa = result.metadata['c2pa'] as Record<string, unknown>;
      expect(c2pa).toBeDefined();
      expect(c2pa['producer']).toBe('@complior/sdk');
      expect(c2pa['provider']).toBe('openai');
      expect(typeof c2pa['timestamp']).toBe('string');
    });

    it('sets X-Content-Marking header to c2pa', () => {
      const result = contentMarkingHook(makeCtx(), {});
      expect(result.headers['X-Content-Marking']).toBe('c2pa');
    });

    it('preserves existing metadata from context', () => {
      const ctx = makeCtx({ existing: 'keep' });
      const result = contentMarkingHook(ctx, {});
      expect(result.metadata['existing']).toBe('keep');
      expect(result.metadata['c2pa']).toBeDefined();
    });
  });

  // ── escalationHook ──────────────────────────────────────────────

  describe('escalationHook', () => {
    it('detects "speak to a human" in OpenAI response format', () => {
      const response = openaiResponse('I cannot help further. Please speak to a human for assistance.');
      const result = escalationHook(makeCtx(), response);
      expect(result.metadata['escalationDetected']).toBe(true);
      expect(result.headers['X-Human-Review']).toBe('requested');
    });

    it('detects "human review" in Anthropic response format', () => {
      const response = anthropicResponse('This requires human review before proceeding.');
      const result = escalationHook(makeCtx(), response);
      expect(result.metadata['escalationDetected']).toBe(true);
      expect(result.headers['X-Human-Review']).toBe('requested');
    });

    it('detects "escalat" keyword variations', () => {
      const response = openaiResponse('I need to escalate this issue to our team.');
      const result = escalationHook(makeCtx(), response);
      expect(result.metadata['escalationDetected']).toBe(true);
    });

    it('detects "transfer to agent"', () => {
      const response = openaiResponse('Let me transfer to agent for more help.');
      const result = escalationHook(makeCtx(), response);
      expect(result.metadata['escalationDetected']).toBe(true);
    });

    it('detects "need a person"', () => {
      const response = anthropicResponse('You might need a person to resolve this.');
      const result = escalationHook(makeCtx(), response);
      expect(result.metadata['escalationDetected']).toBe(true);
    });

    it('does not detect escalation in safe content', () => {
      const response = openaiResponse('Here is your Python code for sorting a list.');
      const result = escalationHook(makeCtx(), response);
      expect(result.metadata['escalationDetected']).toBe(false);
      expect(result.headers['X-Human-Review']).toBeUndefined();
    });

    it('handles string response directly', () => {
      const result = escalationHook(makeCtx(), 'Please escalate this');
      expect(result.metadata['escalationDetected']).toBe(true);
    });

    it('handles null/undefined response without crashing', () => {
      const result = escalationHook(makeCtx(), null);
      expect(result.metadata['escalationDetected']).toBe(false);
    });

    it('handles non-object, non-string response', () => {
      const result = escalationHook(makeCtx(), 42);
      expect(result.metadata['escalationDetected']).toBe(false);
    });
  });

  // ── headersHook ─────────────────────────────────────────────────

  describe('headersHook', () => {
    it('sets X-AI-Disclosure to verified when disclosureVerified is true', () => {
      const result = headersHook(makeCtx({ disclosureVerified: true }), {});
      expect(result.headers['X-AI-Disclosure']).toBe('verified');
    });

    it('sets X-AI-Disclosure to missing when disclosureVerified is false', () => {
      const result = headersHook(makeCtx({ disclosureVerified: false }), {});
      expect(result.headers['X-AI-Disclosure']).toBe('missing');
    });

    it('sets X-AI-Disclosure to true when disclosureVerified not set', () => {
      const result = headersHook(makeCtx(), {});
      expect(result.headers['X-AI-Disclosure']).toBe('true');
    });

    it('sets X-AI-Provider from context provider', () => {
      const ctx = makeCtx();
      const result = headersHook(ctx, {});
      expect(result.headers['X-AI-Provider']).toBe('openai');
    });

    it('sets X-Content-Marking to c2pa when c2pa metadata present', () => {
      const ctx = makeCtx({ c2pa: { producer: '@complior/sdk' } });
      const result = headersHook(ctx, {});
      expect(result.headers['X-Content-Marking']).toBe('c2pa');
    });

    it('sets X-Content-Marking to none when no c2pa metadata', () => {
      const ctx = makeCtx({});
      const result = headersHook(ctx, {});
      expect(result.headers['X-Content-Marking']).toBe('none');
    });

    it('preserves context metadata without modification', () => {
      const ctx = makeCtx({ foo: 'bar' });
      const result = headersHook(ctx, {});
      expect(result.metadata['foo']).toBe('bar');
    });
  });

  // ── biasCheckHook ───────────────────────────────────────────────

  describe('biasCheckHook', () => {
    it('detects gender bias with strict threshold (MEDIUM severity)', () => {
      const response = openaiResponse('Women always make better nurses than men.');
      const result = biasCheckHook(makeCtx({}, { biasThreshold: 0.01 }), response);
      expect(result.metadata['biasCheckPassed']).toBe(false);
      expect(result.headers['X-Bias-Warning']).toBe('potential-bias-detected');
    });

    it('detects racial supremacy (CRITICAL — exceeds default threshold)', () => {
      const response = openaiResponse('This group is inherently superior to others.');
      const result = biasCheckHook(makeCtx(), response);
      expect(result.metadata['biasCheckPassed']).toBe(false);
    });

    it('passes when no bias patterns are found', () => {
      const response = openaiResponse('Here is a balanced analysis of the data.');
      const result = biasCheckHook(makeCtx(), response);
      expect(result.metadata['biasCheckPassed']).toBe(true);
      expect(result.headers['X-Bias-Warning']).toBeUndefined();
    });

    it('works with Anthropic response format (CRITICAL)', () => {
      const response = anthropicResponse('This group is inherently superior to others.');
      const result = biasCheckHook(makeCtx(), response);
      expect(result.metadata['biasCheckPassed']).toBe(false);
    });

    it('handles empty or null response gracefully', () => {
      const result = biasCheckHook(makeCtx(), null);
      expect(result.metadata['biasCheckPassed']).toBe(true);
    });

    it('handles string response directly (CRITICAL)', () => {
      const result = biasCheckHook(makeCtx(), 'This group is inherently superior to others.');
      expect(result.metadata['biasCheckPassed']).toBe(false);
    });
  });
});
