import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { MiddlewareContext, MiddlewareConfig } from '../types.js';
import { extractResponseMeta, extractModel } from '../runtime/response-wrapper.js';
import { createDisclosureInjectorHook } from '../runtime/disclosure-injector.js';
import { contentMarkingHook } from '../hooks/post/content-marking.js';
import { createInteractionLoggerHook } from '../runtime/interaction-logger.js';

vi.mock('node:fs/promises', () => ({
  appendFile: vi.fn().mockResolvedValue(undefined),
  stat: vi.fn().mockResolvedValue({ size: 0 }),
  rename: vi.fn().mockResolvedValue(undefined),
  mkdir: vi.fn().mockResolvedValue(undefined),
}));

const makeCtx = (config: MiddlewareConfig = {}, metadata: Record<string, unknown> = {}): MiddlewareContext => ({
  provider: 'openai',
  method: 'create',
  config,
  params: { model: 'gpt-4', messages: [{ role: 'user', content: 'Hello' }] },
  metadata,
});

const openaiResponse = (text: string, model = 'gpt-4') => ({
  model,
  choices: [{ message: { content: text } }],
  usage: { prompt_tokens: 10, completion_tokens: 20 },
});

const anthropicResponse = (text: string, model = 'claude-3-opus') => ({
  model,
  content: [{ type: 'text', text }],
  usage: { input_tokens: 15, output_tokens: 25 },
});

describe('response-wrapper', () => {
  it('extracts model from OpenAI response', () => {
    expect(extractModel(openaiResponse('hi'))).toBe('gpt-4');
  });

  it('extracts model from Anthropic response', () => {
    expect(extractModel(anthropicResponse('hi'))).toBe('claude-3-opus');
  });

  it('extracts tokens from usage fields', () => {
    const meta = extractResponseMeta(openaiResponse('hi'));
    expect(meta.inputTokens).toBe(10);
    expect(meta.outputTokens).toBe(20);

    const metaA = extractResponseMeta(anthropicResponse('hi'));
    expect(metaA.inputTokens).toBe(15);
    expect(metaA.outputTokens).toBe(25);
  });

  it('returns defaults for unknown format', () => {
    const meta = extractResponseMeta({ foo: 'bar' });
    expect(meta.model).toBe('unknown');
    expect(meta.inputTokens).toBe(0);
    expect(meta.outputTokens).toBe(0);
  });
});

describe('disclosure-injector', () => {
  it('skips when disclosureInjection is false', () => {
    const hook = createDisclosureInjectorHook({ disclosureInjection: false });
    const result = hook(makeCtx(), openaiResponse('Hello'));
    expect(result.metadata['disclosureResponseInjected']).toBeUndefined();
  });

  it('prepends text to OpenAI response', () => {
    const hook = createDisclosureInjectorHook({
      disclosureInjection: true,
      disclosurePosition: 'prepend',
    });
    const result = hook(makeCtx(), openaiResponse('Hello world'));
    const choices = (result.response as Record<string, unknown>)['choices'] as Array<Record<string, unknown>>;
    const msg = choices[0]!['message'] as Record<string, unknown>;
    expect(msg['content']).toBe('This content was generated by AI.\n\nHello world');
    expect(result.metadata['disclosureResponseInjected']).toBe(true);
    expect(result.metadata['disclosurePosition']).toBe('prepend');
  });

  it('appends text to Anthropic response', () => {
    const hook = createDisclosureInjectorHook({
      disclosureInjection: true,
      disclosurePosition: 'append',
    });
    const result = hook(makeCtx(), anthropicResponse('Hello world'));
    const content = (result.response as Record<string, unknown>)['content'] as Array<Record<string, unknown>>;
    expect(content[0]!['text']).toBe('Hello world\n\nThis content was generated by AI.');
  });

  it('adds header when position=header', () => {
    const hook = createDisclosureInjectorHook({
      disclosureInjection: true,
      disclosurePosition: 'header',
    });
    const result = hook(makeCtx(), openaiResponse('Hello'));
    expect(result.headers['X-AI-Disclosure-Text']).toBe('This content was generated by AI.');
    expect(result.metadata['disclosurePosition']).toBe('header');
  });

  it('uses custom disclosureText', () => {
    const hook = createDisclosureInjectorHook({
      disclosureInjection: true,
      disclosureText: 'AI generated content',
      disclosurePosition: 'prepend',
    });
    const result = hook(makeCtx(), openaiResponse('Body'));
    const choices = (result.response as Record<string, unknown>)['choices'] as Array<Record<string, unknown>>;
    const msg = choices[0]!['message'] as Record<string, unknown>;
    expect(msg['content']).toBe('AI generated content\n\nBody');
  });

  it('session-start: injects on first call only', () => {
    const hook = createDisclosureInjectorHook({
      disclosureInjection: true,
      disclosureFrequency: 'session-start',
    });
    const r1 = hook(makeCtx(), openaiResponse('First'));
    expect(r1.metadata['disclosureResponseInjected']).toBe(true);
  });

  it('session-start: skips subsequent calls', () => {
    const hook = createDisclosureInjectorHook({
      disclosureInjection: true,
      disclosureFrequency: 'session-start',
    });
    hook(makeCtx(), openaiResponse('First'));
    const r2 = hook(makeCtx(), openaiResponse('Second'));
    expect(r2.metadata['disclosureResponseInjected']).toBeUndefined();
  });
});

describe('content-marking enhanced', () => {
  it('includes model from response', () => {
    const result = contentMarkingHook(makeCtx(), openaiResponse('hi', 'gpt-4-turbo'));
    const c2pa = result.metadata['c2pa'] as Record<string, unknown>;
    expect(c2pa['model']).toBe('gpt-4-turbo');
  });

  it('includes complianceScore from metadata', () => {
    const ctx = makeCtx({}, { disclosureVerified: true, biasCheckPassed: true, sanitized: true });
    const result = contentMarkingHook(ctx, openaiResponse('hi'));
    const c2pa = result.metadata['c2pa'] as Record<string, unknown>;
    expect(c2pa['complianceScore']).toBe(100);
  });

  it('score is 100 when all checks pass', () => {
    const ctx = makeCtx({}, { disclosureVerified: true, piiHandled: true });
    const result = contentMarkingHook(ctx, openaiResponse('hi'));
    const c2pa = result.metadata['c2pa'] as Record<string, unknown>;
    // disclosure=25, bias(not false)=25, piiHandled=25, noEscalation=25 = 100
    expect(c2pa['complianceScore']).toBe(100);
  });

  it('score is 0 with empty metadata', () => {
    const ctx = makeCtx({}, { biasCheckPassed: false, escalationDetected: true });
    const result = contentMarkingHook(ctx, openaiResponse('hi'));
    const c2pa = result.metadata['c2pa'] as Record<string, unknown>;
    // disclosure=0, bias=0, pii=0, escalation=0 = 0
    expect(c2pa['complianceScore']).toBe(0);
  });
});

describe('interaction-logger', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('skips when interactionLogger is false', () => {
    const hook = createInteractionLoggerHook({ interactionLogger: false });
    const result = hook(makeCtx(), openaiResponse('hi'));
    expect(result.metadata['interactionLogged']).toBeUndefined();
  });

  it('sets interactionLogged metadata', () => {
    const hook = createInteractionLoggerHook({ interactionLogger: true });
    const result = hook(
      makeCtx({ interactionLogger: true }, { loggedAtMs: Date.now() }),
      openaiResponse('hi'),
    );
    expect(result.metadata['interactionLogged']).toBe(true);
  });

  it('computes SHA-256 hashes', async () => {
    const { createHash } = await import('node:crypto');
    const hook = createInteractionLoggerHook({ interactionLogger: true });
    const params = { model: 'gpt-4', messages: [{ role: 'user', content: 'Hello' }] };
    const ctx = makeCtx({ interactionLogger: true }, { loggedAtMs: Date.now() });
    ctx.params = params;
    hook(ctx, openaiResponse('Response text'));

    // Verify appendFile was called with valid JSON containing hashes
    const { appendFile } = await import('node:fs/promises');
    // Allow async tick for fire-and-forget
    await new Promise((r) => setTimeout(r, 10));
    expect(appendFile).toHaveBeenCalled();
    const callArgs = (appendFile as ReturnType<typeof vi.fn>).mock.calls[0] as [string, string];
    const entry = JSON.parse(callArgs[1]!) as Record<string, unknown>;
    expect(entry['promptHash']).toBe(
      createHash('sha256').update(JSON.stringify(params)).digest('hex'),
    );
    expect(entry['responseHash']).toBe(
      createHash('sha256').update('Response text').digest('hex'),
    );
  });

  it('builds complianceChecks from metadata', async () => {
    const hook = createInteractionLoggerHook({ interactionLogger: true });
    hook(
      makeCtx({ interactionLogger: true }, {
        loggedAtMs: Date.now(),
        disclosureVerified: true,
        biasCheckPassed: false,
        piiRedactedCount: 3,
        escalationDetected: true,
      }),
      openaiResponse('hi'),
    );

    const { appendFile } = await import('node:fs/promises');
    await new Promise((r) => setTimeout(r, 10));
    expect(appendFile).toHaveBeenCalled();
    const callArgs = (appendFile as ReturnType<typeof vi.fn>).mock.calls[0] as [string, string];
    const entry = JSON.parse(callArgs[1]!) as Record<string, unknown>;
    const checks = entry['complianceChecks'] as Record<string, unknown>;
    expect(checks['disclosureVerified']).toBe(true);
    expect(checks['biasCheckPassed']).toBe(false);
    expect(checks['piiRedacted']).toBe(3);
    expect(checks['escalationDetected']).toBe(true);
  });
});
