import type { OnboardingProfile } from '../../onboarding/profile.js';

export interface GeneratedConfig {
  readonly type: 'docker-compose' | 'env' | 'ci-cd';
  readonly filename: string;
  readonly content: string;
  readonly description: string;
  readonly changes: readonly string[];
}

export const generateDockerCompose = (profile: OnboardingProfile): GeneratedConfig => {
  const services: string[] = [];
  const changes: string[] = [];

  services.push(`  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AI_DISCLOSURE_ENABLED=true
      - AUDIT_LOG_ENABLED=true
      - COMPLIANCE_MODE=strict
    depends_on:
      - audit-db`);
  changes.push('App service with compliance environment variables');

  services.push(`  audit-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: complior_audit
      POSTGRES_PASSWORD: \${AUDIT_DB_PASSWORD}
    volumes:
      - audit-data:/var/lib/postgresql/data`);
  changes.push('Audit trail database (PostgreSQL)');

  if (profile.computed.riskLevel === 'high') {
    services.push(`  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml`);
    changes.push('Monitoring service (Prometheus) for high-risk AI');
  }

  const content = `# Compliance-enhanced Docker Compose
# Generated by Complior for ${profile.business.domain} domain (${profile.computed.riskLevel} risk)

version: "3.9"

services:
${services.join('\n\n')}

volumes:
  audit-data:
`;

  return Object.freeze({
    type: 'docker-compose',
    filename: 'docker-compose.compliance.yml',
    content,
    description: `Docker Compose with compliance services for ${profile.computed.riskLevel} risk ${profile.business.domain} project`,
    changes,
  });
};

export const generateEnvExample = (profile: OnboardingProfile): GeneratedConfig => {
  const lines: string[] = [
    '# Compliance Environment Variables',
    `# Generated by Complior for ${profile.business.domain} domain`,
    '',
    '# === AI Disclosure (Art. 50) ===',
    'AI_DISCLOSURE_ENABLED=true',
    'AI_DISCLOSURE_TEXT="This service uses artificial intelligence"',
    '',
    '# === Audit Logging (Art. 12) ===',
    'AUDIT_LOG_ENABLED=true',
    'AUDIT_LOG_RETENTION_DAYS=365',
    'AUDIT_DB_PASSWORD=changeme',
    '',
    '# === Human Oversight (Art. 14) ===',
    'HUMAN_ESCALATION_ENABLED=true',
    'HUMAN_ESCALATION_THRESHOLD=0.7',
  ];

  const changes: string[] = ['AI disclosure toggle', 'Audit logging config', 'Human oversight threshold'];

  if (profile.computed.riskLevel === 'high') {
    lines.push(
      '',
      '# === High-Risk Monitoring (Art. 9) ===',
      'MONITORING_ENDPOINT=http://localhost:9090',
      'BIAS_TESTING_ENABLED=true',
      'BIAS_TESTING_SCHEDULE=weekly',
    );
    changes.push('Monitoring endpoint', 'Bias testing schedule');
  }

  if (profile.data.types.includes('personal') || profile.data.types.includes('health')) {
    lines.push(
      '',
      '# === Data Protection ===',
      'DATA_RETENTION_DAYS=90',
      'DATA_ENCRYPTION_AT_REST=true',
      'DATA_ANONYMIZATION_ENABLED=true',
    );
    changes.push('Data protection settings');
  }

  return Object.freeze({
    type: 'env',
    filename: '.env.compliance.example',
    content: lines.join('\n') + '\n',
    description: 'Compliance environment variables with defaults',
    changes,
  });
};

export const generateCIWorkflow = (profile: OnboardingProfile): GeneratedConfig => {
  const changes: string[] = ['Pre-push compliance scan', 'Weekly audit report'];

  const content = `# Compliance CI/CD Workflow
# Generated by Complior

name: Compliance Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * 1'  # Weekly Monday 9am

jobs:
  compliance-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Complior
        run: npm install -g complior

      - name: Run Compliance Scan
        run: complior scan --ci --threshold ${profile.computed.riskLevel === 'high' ? 70 : 50} --sarif results.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  weekly-audit:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Complior
        run: npm install -g complior

      - name: Generate Audit Report
        run: complior scan --ci --json > audit-report.json

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: compliance-audit-\${{ github.run_number }}
          path: audit-report.json
`;

  return Object.freeze({
    type: 'ci-cd',
    filename: '.github/workflows/compliance-check.yml',
    content,
    description: 'GitHub Actions workflow for compliance scanning and weekly audits',
    changes,
  });
};

export const generateAllConfigs = (profile: OnboardingProfile): readonly GeneratedConfig[] => {
  return [
    generateDockerCompose(profile),
    generateEnvExample(profile),
    generateCIWorkflow(profile),
  ];
};
