import { describe, it, expect } from 'vitest';
import { resolve } from 'node:path';
import { mkdtemp, readFile, access, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import type { ScanResult, Finding, ScoreBreakdown } from '../types/common.types.js';
import { installHooks } from './installer.js';
import { toGithubIssue } from '../output/github-issue.js';
import { toJiraCsv } from '../output/jira-csv.js';

// --- Helpers ---

const makeScore = (overrides?: Partial<ScoreBreakdown>): ScoreBreakdown => ({
  totalScore: 42,
  zone: 'red',
  categoryScores: [],
  criticalCapApplied: false,
  totalChecks: 10,
  passedChecks: 4,
  failedChecks: 5,
  skippedChecks: 1,
  ...overrides,
});

const makeFinding = (overrides?: Partial<Finding>): Finding => ({
  checkId: 'test-check',
  type: 'fail',
  message: 'Test failure',
  severity: 'high',
  ...overrides,
});

const makeResult = (overrides?: Partial<ScanResult>): ScanResult => ({
  score: makeScore(),
  findings: [
    makeFinding({ checkId: 'ai-disclosure', severity: 'high', articleReference: 'Art. 50(1)', fix: 'Add disclosure' }),
    makeFinding({ checkId: 'logging', severity: 'medium', file: 'src/app.ts' }),
  ],
  projectPath: '/test',
  scannedAt: '2026-01-01T00:00:00Z',
  duration: 100,
  filesScanned: 50,
  ...overrides,
});

// --- Hook install tests ---

describe('installHooks', () => {
  let tmpDir: string;

  it('installs 3 hooks in .git/hooks/', async () => {
    tmpDir = await mkdtemp(resolve(tmpdir(), 'complior-hooks-'));
    const { mkdir } = await import('node:fs/promises');
    await mkdir(resolve(tmpDir, '.git', 'hooks'), { recursive: true });

    const installed = await installHooks(tmpDir);
    expect(installed).toEqual(['pre-commit', 'pre-push', 'commit-msg']);

    // Verify files exist
    for (const name of installed) {
      await access(resolve(tmpDir, '.git', 'hooks', name));
      const content = await readFile(resolve(tmpDir, '.git', 'hooks', name), 'utf-8');
      expect(content).toContain('complior');
    }

    await rm(tmpDir, { recursive: true });
  });
});

// --- GitHub Issue export ---

describe('toGithubIssue', () => {
  it('produces Markdown checklist', () => {
    const md = toGithubIssue(makeResult());
    expect(md).toContain('## EU AI Act Compliance Checklist');
    expect(md).toContain('- [ ] **[HIGH]** ai-disclosure');
    expect(md).toContain('Art. 50(1)');
    expect(md).toContain('Fix: Add disclosure');
    expect(md).toContain('Generated by [Complior]');
  });
});

// --- Jira CSV export ---

describe('toJiraCsv', () => {
  it('produces valid CSV', () => {
    const csv = toJiraCsv(makeResult());
    expect(csv).toContain('Summary,Description,Priority,Labels,Component');
    expect(csv).toContain('ai-disclosure');
    expect(csv).toContain('High');
    expect(csv).toContain('Medium');
    // 2 findings: count [Compliance] prefixes in summary column
    const matches = csv.match(/\[Compliance\]/g);
    expect(matches).toHaveLength(2);
  });
});
