export const AI_SDK_PACKAGES: ReadonlyMap<string, string> = new Map([
  // npm
  ['openai', 'OpenAI'],
  ['@anthropic-ai/sdk', 'Anthropic'],
  ['anthropic', 'Anthropic'],
  ['@google/generative-ai', 'Google AI'],
  ['@google-cloud/aiplatform', 'Google Vertex AI'],
  ['cohere-ai', 'Cohere'],
  ['@mistralai/mistralai', 'Mistral'],
  ['ai', 'Vercel AI SDK'],
  ['@ai-sdk/openai', 'Vercel AI SDK (OpenAI)'],
  ['@ai-sdk/anthropic', 'Vercel AI SDK (Anthropic)'],
  ['@ai-sdk/google', 'Vercel AI SDK (Google)'],
  ['@ai-sdk/mistral', 'Vercel AI SDK (Mistral)'],
  ['@ai-sdk/amazon-bedrock', 'Vercel AI SDK (Bedrock)'],
  ['langchain', 'LangChain'],
  ['@langchain/core', 'LangChain Core'],
  ['@langchain/openai', 'LangChain (OpenAI)'],
  ['@langchain/anthropic', 'LangChain (Anthropic)'],
  ['@langchain/community', 'LangChain (Community)'],
  ['llamaindex', 'LlamaIndex'],
  ['replicate', 'Replicate'],
  ['huggingface', 'Hugging Face'],
  ['@huggingface/inference', 'Hugging Face Inference'],
  ['@openclaw/sdk', 'OpenClaw'],
  ['groq-sdk', 'Groq'],
  ['ollama', 'Ollama'],
  ['@aws-sdk/client-bedrock-runtime', 'Amazon Bedrock'],
  ['@azure/openai', 'Azure OpenAI'],
  // pip
  ['google-generativeai', 'Google AI'],
  ['cohere', 'Cohere'],
  ['mistralai', 'Mistral'],
  ['llama-index', 'LlamaIndex'],
  ['transformers', 'Hugging Face Transformers'],
  ['torch', 'PyTorch'],
  ['tensorflow', 'TensorFlow'],
  ['crewai', 'CrewAI'],
  ['pyautogen', 'AutoGen'],
  ['groq', 'Groq'],
  ['together', 'Together AI'],
  ['fireworks-ai', 'Fireworks AI'],
  ['litellm', 'LiteLLM'],
  ['semantic-kernel', 'Semantic Kernel'],
  ['haystack-ai', 'Haystack'],
  ['instructor', 'Instructor'],
  ['dspy-ai', 'DSPy'],
  ['phidata', 'Phidata'],
  ['boto3', 'AWS SDK (Bedrock)'],
  ['deepseek-sdk', 'DeepSeek'],
  // cargo
  ['async-openai', 'OpenAI (Rust)'],
  ['llm', 'LLM (Rust)'],
  // go
  ['github.com/sashabaranov/go-openai', 'OpenAI (Go)'],
  ['github.com/anthropics/anthropic-sdk-go', 'Anthropic (Go)'],
]);

export const BIAS_TESTING_PACKAGES: ReadonlySet<string> = new Set([
  'fairlearn',
  'aif360',
  'aequitas',
  'responsibleai',
  '@responsible-ai/fairness',
]);
