import type { ScanResult } from '../types/common.types.js';

export const toGithubIssue = (result: ScanResult): string => {
  const failFindings = result.findings.filter((f) => f.type === 'fail');
  const lines: string[] = [
    '## EU AI Act Compliance Checklist',
    '',
    `**Score:** ${result.score.totalScore}/100 (${result.score.zone.toUpperCase()})`,
    `**Scanned:** ${result.scannedAt}`,
    `**Files:** ${result.filesScanned}`,
    '',
    '### Findings',
    '',
  ];

  if (failFindings.length === 0) {
    lines.push('No violations found.');
  } else {
    for (const f of failFindings) {
      const ref = f.articleReference ? ` (${f.articleReference})` : '';
      const file = f.file ? ` — \`${f.file}\`` : '';
      lines.push(`- [ ] **[${f.severity.toUpperCase()}]** ${f.checkId}${ref}: ${f.message}${file}`);
      if (f.fix) {
        lines.push(`  - Fix: ${f.fix}`);
      }
    }
  }

  lines.push('', '---', '*Generated by [Complior](https://complior.ai)*');

  return lines.join('\n');
};
