export type DisclaimerContext = 'system_prompt' | 'report_footer' | 'compliance_md' | 'commit_message' | 'chat_response';

const DISCLAIMERS: Record<DisclaimerContext, string> = {
  system_prompt: 'You are Complior, a compliance ASSISTANT — not a legal advisor. You NEVER state that a project "is compliant" or "meets all requirements". You ALWAYS frame results as "based on automated scanning" and recommend professional legal review for definitive compliance assessment.',

  report_footer: `---
**Disclaimer:** This report was generated by Complior automated scanning tool. It does NOT constitute legal advice. For definitive compliance assessment, consult a qualified legal professional specializing in EU AI Act.`,

  compliance_md: `## Disclaimer

This compliance status is based on automated scanning by Complior. It is NOT a legal certification. Professional legal review is recommended before making compliance claims.`,

  commit_message: 'Auto-generated by Complior. Review before merging. Automated fix — not legal advice.',

  chat_response: 'Disclaimer: Complior — automated scanning tool, not a legal advisor. Professional review recommended.',
};

export const getDisclaimer = (context: DisclaimerContext): string => DISCLAIMERS[context];

export const appendDisclaimer = (content: string, context: DisclaimerContext): string =>
  `${content}\n\n${DISCLAIMERS[context]}`;

export const getReportFooter = (version: string): string =>
  `${DISCLAIMERS.report_footer}\nGenerated: ${new Date().toISOString().slice(0, 10)} | Scanner: complior v${version}`;

// Banned phrases that LLM should never output
export const BANNED_PHRASES = [
  'you are compliant',
  'your project is compliant',
  'meets all requirements',
  'fully compliant',
  'no violations found', // when score < 100
  'I guarantee compliance',
] as const;

export const containsBannedPhrase = (text: string): boolean => {
  const lower = text.toLowerCase();
  return BANNED_PHRASES.some((phrase) => lower.includes(phrase.toLowerCase()));
};
