import type { ScanResult } from '../../types/common.types.js';

export const generateComplianceMd = (result: ScanResult, version: string): string => {
  const { score, findings, scannedAt } = result;
  const failFindings = findings.filter((f) => f.type === 'fail');
  const topIssues = failFindings
    .sort((a, b) => {
      const sevOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 } as const;
      return sevOrder[a.severity] - sevOrder[b.severity];
    })
    .slice(0, 5);

  const findingsTable = failFindings.length > 0
    ? `| Check ID | Severity | Message |
|----------|----------|---------|
${failFindings.map((f) => `| ${f.checkId} | ${f.severity} | ${f.message} |`).join('\n')}`
    : '_No compliance issues found._';

  const topIssuesList = topIssues.length > 0
    ? topIssues.map((f, i) => `${i + 1}. **[${f.severity.toUpperCase()}]** ${f.checkId}: ${f.message}`).join('\n')
    : '_None_';

  return `# Compliance Report

> Generated by Complior v${version} on ${scannedAt}

## Score

| Metric | Value |
|--------|-------|
| Total Score | **${score.totalScore}%** |
| Zone | ${score.zone} |
| Checks | ${score.totalChecks} total, ${score.passedChecks} passed, ${score.failedChecks} failed |

## Findings Summary

${findingsTable}

## Top Issues

${topIssuesList}

---

![Compliance Badge](.complior/badge.svg)
`;
};
