export interface DisclosurePhrase {
  readonly pattern: RegExp;
  readonly language: 'EN' | 'DE' | 'FR' | 'ES';
  readonly description: string;
}

export const DISCLOSURE_PHRASES: readonly DisclosurePhrase[] = Object.freeze([
  // EN — English
  { pattern: /AI[- ]generated/i, language: 'EN', description: 'AI-generated' },
  { pattern: /artificial\s*intelligence/i, language: 'EN', description: 'artificial intelligence' },
  { pattern: /generated\s*by\s*(?:an?\s*)?AI/i, language: 'EN', description: 'generated by AI' },
  { pattern: /AI\s*system/i, language: 'EN', description: 'AI system' },
  { pattern: /machine[- ]generated/i, language: 'EN', description: 'machine-generated' },

  // DE — German
  { pattern: /KI[- ]generiert/i, language: 'DE', description: 'KI-generiert' },
  { pattern: /künstliche\s*Intelligenz/i, language: 'DE', description: 'künstliche Intelligenz' },
  { pattern: /(?:von|durch)\s*(?:einer?\s*)?KI\s*(?:generiert|erstellt|erzeugt)/i, language: 'DE', description: 'von KI generiert' },
  { pattern: /KI[- ]System/i, language: 'DE', description: 'KI-System' },

  // FR — French
  { pattern: /généré\s*par\s*(?:l['']?\s*)?IA/i, language: 'FR', description: "généré par l'IA" },
  { pattern: /intelligence\s*artificielle/i, language: 'FR', description: 'intelligence artificielle' },
  { pattern: /système\s*d['']?\s*IA/i, language: 'FR', description: "système d'IA" },
  { pattern: /contenu\s*(?:généré|produit)\s*(?:par\s*)?(?:l['']?\s*)?(?:IA|intelligence\s*artificielle)/i, language: 'FR', description: "contenu généré par l'IA" },

  // ES — Spanish
  { pattern: /generado\s*por\s*(?:la\s*)?IA/i, language: 'ES', description: 'generado por IA' },
  { pattern: /inteligencia\s*artificial/i, language: 'ES', description: 'inteligencia artificial' },
  { pattern: /sistema\s*de\s*IA/i, language: 'ES', description: 'sistema de IA' },
  { pattern: /contenido\s*(?:generado|producido)\s*(?:por\s*)?(?:la\s*)?(?:IA|inteligencia\s*artificial)/i, language: 'ES', description: 'contenido generado por IA' },
]);
