import type { FixStrategy, FixAction } from '../types.js';
import { generateCreateDiff } from '../diff.js';
import { ENGINE_VERSION } from '../../../version.js';

// --- Strategy: Bandit Fix (Art. 15.4) ---

const BANDIT_FIXES: Record<string, { issue: string; fix: string }> = {
  'B301': { issue: 'Use of pickle (deserialization risk)', fix: 'Replace pickle with json or yaml for data serialization' },
  'B603': { issue: 'subprocess call with shell=True', fix: 'Use subprocess.run() with a list of arguments instead of shell=True' },
  'B608': { issue: 'SQL injection via string formatting', fix: 'Use parameterized queries instead of string concatenation' },
  'B105': { issue: 'Hardcoded password in source code', fix: 'Move password to environment variable or secrets manager' },
};

export const banditFixStrategy: FixStrategy = (finding, context) => {
  if (!finding.checkId.startsWith('ext-bandit-')) return null;

  const ruleId = finding.checkId.replace('ext-bandit-', '').toUpperCase();
  const known = BANDIT_FIXES[ruleId];

  const lines = [`# Security Fixes — Bandit Findings\n`];
  lines.push(`Generated by Complior v${ENGINE_VERSION}\n`);

  if (known) {
    lines.push(`## ${ruleId}: ${known.issue}\n`);
    lines.push(`**Fix:** ${known.fix}\n`);
  } else {
    lines.push(`## ${ruleId}: Security finding\n`);
    lines.push(`**Fix:** Review the flagged code and apply the recommended remediation from Bandit documentation.\n`);
  }

  if (finding.message) {
    lines.push(`### Details\n`);
    lines.push(`${finding.message}\n`);
  }

  lines.push(`## Verification\n`);
  lines.push(`- [ ] Fix applied\n- [ ] Re-run \`bandit\` to verify\n- [ ] Peer review completed\n`);

  const content = lines.join('\n');
  const filePath = 'complior-security-fixes.md';

  const action: FixAction = {
    type: 'create',
    path: filePath,
    content,
    description: `Create security fix plan for Bandit ${ruleId}`,
  };

  return {
    obligationId: finding.obligationId ?? 'eu-ai-act-OBL-008',
    checkId: finding.checkId,
    article: finding.articleReference ?? 'Art. 15(4)',
    fixType: 'template_generation',
    framework: context.framework,
    actions: [action],
    diff: generateCreateDiff(filePath, content),
    scoreImpact: 4,
    commitMessage: `fix: add Bandit ${ruleId} remediation plan (Art. 15.4) -- via Complior`,
    description: `Create security remediation plan for Bandit finding ${ruleId}`,
  };
};
