import type { FixStrategy, FixAction } from '../types.js';
import { generateCreateDiff } from '../diff.js';
import { ENGINE_VERSION } from '../../../version.js';

// --- Strategy: Doc-Code Sync (Art. 11) ---

export const docCodeSyncStrategy: FixStrategy = (finding, context) => {
  if (finding.checkId !== 'cross-doc-code-mismatch') return null;

  const filePath = 'complior-doc-sync-report.md';
  const content = `# Documentation-Code Sync Report

Generated by Complior v${ENGINE_VERSION}

## Mismatch Detected

${finding.message || 'Documentation does not match the current codebase implementation.'}

## Checklist

- [ ] Review flagged documentation sections
- [ ] Update technical documentation to match current implementation
- [ ] Verify API documentation reflects actual endpoints and parameters
- [ ] Check that architecture diagrams are up to date
- [ ] Run \`complior scan\` to verify documentation coverage

## Auto-generate Missing Docs

\`\`\`bash
complior docs generate --missing
\`\`\`
`;

  const action: FixAction = {
    type: 'create',
    path: filePath,
    content,
    description: 'Create documentation-code sync report',
  };

  return {
    obligationId: finding.obligationId ?? 'eu-ai-act-OBL-005',
    checkId: finding.checkId,
    article: finding.articleReference ?? 'Art. 11',
    fixType: 'template_generation',
    framework: context.framework,
    actions: [action],
    diff: generateCreateDiff(filePath, content),
    scoreImpact: 5,
    commitMessage: 'fix: add doc-code sync report (Art. 11) -- via Complior',
    description: 'Create report documenting mismatches between code and documentation',
  };
};
