import type { FixStrategy, FixAction } from '../types.js';
import { generateCreateDiff } from '../diff.js';
import { ENGINE_VERSION } from '../../../version.js';

// --- Strategy: License Fix (Art. 5) ---

export const licenseFixStrategy: FixStrategy = (finding, context) => {
  if (finding.checkId !== 'l3-dep-license') return null;

  const filePath = 'complior-license-review.md';
  const content = `# License Compliance Review

Generated by Complior v${ENGINE_VERSION}

## Issue

${finding.message || 'Dependency with incompatible or problematic license detected.'}

## License Compatibility Matrix

| License | Commercial Use | Modification | Distribution | Patent Grant |
|---------|---------------|-------------|-------------|-------------|
| MIT     | Yes           | Yes         | Yes         | No          |
| Apache-2.0 | Yes       | Yes         | Yes         | Yes         |
| GPL-3.0 | Copyleft      | Copyleft    | Copyleft    | Yes         |
| AGPL-3.0 | Copyleft     | Copyleft    | Copyleft (network) | Yes  |
| SSPL    | Restricted    | Copyleft    | Copyleft    | No          |

## Action Items

- [ ] Identify the problematic dependency and its license
- [ ] Search for an alternative package with a compatible license
- [ ] Run \`npx license-checker\` or \`pip-licenses\` for a full audit
- [ ] Update dependency and verify license compatibility
- [ ] Document license decision in compliance records
`;

  const action: FixAction = {
    type: 'create',
    path: filePath,
    content,
    description: 'Create license compliance review document',
  };

  return {
    obligationId: finding.obligationId ?? 'eu-ai-act-OBL-002',
    checkId: finding.checkId,
    article: finding.articleReference ?? 'Art. 5',
    fixType: 'dependency_fix',
    framework: context.framework,
    actions: [action],
    diff: generateCreateDiff(filePath, content),
    scoreImpact: 4,
    commitMessage: 'fix: add license compliance review (Art. 5) -- via Complior',
    description: 'Create license review document for dependency with problematic license',
  };
};
