import type { FixStrategy, FixAction } from '../types.js';
import { generateCreateDiff } from '../diff.js';

export const logRetentionStrategy: FixStrategy = (finding, context) => {
  if (finding.checkId !== 'cross-logging-no-retention') return null;

  const composePath = 'docker-compose.override.yml';
  const content = `# Docker Compose Override — Log Retention (EU AI Act, Art. 12)
# Generated by Complior: ensures container logs are retained >= 180 days.
# Merge with your main docker-compose.yml via "docker compose up".

services:
  app:
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "60"
        tag: "{{.Name}}/{{.ID}}"
`;
  const action: FixAction = {
    type: 'create',
    path: composePath,
    content,
    description: 'Create docker-compose.override.yml with log retention config',
  };

  return {
    obligationId: finding.obligationId ?? 'eu-ai-act-OBL-006',
    checkId: finding.checkId,
    article: finding.articleReference ?? 'Art. 12',
    fixType: 'config_fix',
    framework: context.framework,
    actions: [action],
    diff: generateCreateDiff(composePath, content),
    scoreImpact: 4,
    commitMessage: 'fix: add docker-compose log retention override (Art. 12) -- via Complior',
    description: 'Add docker-compose.override.yml with logging retention config for Art. 12 compliance',
  };
};
